### ISSUE TITLE
Alternate trigger mechanism: Unchorded or Modal commands

### ISSUE THREAD

**Issue by robacarp** [jigish/slate#100]
First off, I'm impressed.  Good work here.  :clap:

I read a good portion of the readme, cmd-f'd around for a few keywords in there too, and read the titles of all the open and closed issues and didn't find anything like this. Hopefully I'm not just creating spam here.

Keyboard chording is something I try and do as little of as possible to keep my RSI at bay.  As such, I had my Divvy setup configured with only application-wide shortcuts, and F6 launched the Divvy window.  The paradigm became: F6 then 0, to quickly shove my browser window up to the top-right corner, or F6 then 1 to take up the whole screen, or F6 then 6 to give me a centered window, etc.  All of the commands were single keystroke arrangements, but prefixed by the mode-trigger F6.

A benefit of this is that I was able to map out many many window sizes and placements without really impacting the global key command space.  The entire number row and the entire top row of the keyboard are all mapped to a few different things.   The mapping would simplify greatly using your layouts and snapshots feature, but my personal preference would still be to have a modal interface rather than a chorded.  (cough _vimuser_ :-)

I'm pretty sure I'm an outlier here, and that it might just be a major rework of your code to support a feature like this, but I thought I'd drop it in the suggestion box anyway...for a rainy day.

Thanks again for a well done window manager!

**Comment by jigish** [comment]
Ah good call. This makes a lot of sense. I'll try to add this soon.

**Comment by robacarp** [comment]
Glad to hear it.  I wish I was more proficient at objective-c, I'd outline an implementation.  :-/

**Comment by SethMilliken** [comment]
@robacarp I'd be very surprised if you're an outlier. This project is like a neodymium magnet for terminal editor and multiplexer vets on OS X. :smile:

**Comment by jigish** [comment]
Forgot to update this. This is done in 1.0.7 (we're up to 1.0.9 now). Here is an example:

```
bind 1:f6 move screenOriginX;screenOriginY screenSizeX;screenSizeY
```

This will cause f6 to become a modal key. You press f6 and the slate icon on your menu bar will turn blue to indicate you are in modal mode. Then you press 1 and the binding will activate. Currently I haven't added any way to cancel modal mode. Do you think that is something that would be useful?

**Comment by jigish** [comment]
Also you can use any key in the list of allowed keys in the readme as a modal key.

**Comment by robacarp** [comment]
This is perfect.  Thanks @jigish, top notch.

**Comment by hjon** [comment]
Maybe this is no longer in the spirit of this request, but would it also be possible to use more than one key for modal? For example, I've had Alt-` as a global shortcut for another window management program, similar to @robacarp.

**Comment by SethMilliken** [comment]
@jigish This is a great addition. Any chance of allowing the modal key to include modifiers? (I'm currently using e.g. `Command-Control-w` mapped to `f17` with KeyRemap4MacBook in order to work around this, so not a huge deal for me, but I'm sure others would appreciate it).

**Comment by jigish** [comment]
Good call. Issue #125 will track it.

**Comment by v-yarotsky** [comment]
It would be great to have some kind of 'sticky' modal key option,
so I can press my modal key and then use corresponding key bindings (preferably with other key modifiers) N times, until I hit the modal key again, or some special combination (such as Esc).
Something similar to resizing panes in tmux - hit ctrl+b, then press arrows while holding alt.
What do you think?
