### ISSUE TITLE
Window hints can't pull focus away from a window where a text-input is focused

### ISSUE THREAD

**Issue by robacarp** [jigish/slate#102]
I'm not sure if this is macvim listening in a way it shouldn't or something, but I can window-hint focus into macvim, but not out of it.

I've just noticed that if I have a text area focused in this window, chrome, and I open window hints, any of the hints I target just fire through to the currently active window.

Maybe that means I'm misunderstanding the purpose of window hints...

**Comment by jigish** [comment]
This is really interesting. I just tried to make sure on my machine and it seems to work fine. I'm currently running OS X 10.7.4 and the latest Slate (1.0.5). What versions are you running? Also, if you can consistently repro then it would be really helpful if you could open "Current Window Info" from the Slate menu screen cap the contents here (I need to make it selectable. keep forgetting to do that).

**Comment by robacarp** [comment]
I'm on OSX 10.7.4 as well, and Slate 1.0.5.  I've tried a few combinations, but even on this comment box it types text while the hints are up, then they just fade away.

[Screen capped Current Window Info](http://robacarp.com/images/skitchd/Slate_-_Current_Window_Info-20121002-115913.png)

Fun fact, the Current Window Info box went SWOD on me after the second time opening it... :-/

**Comment by jigish** [comment]
Sorry, one last thing. Can I get a copy of your .slate? I'll try it out on my machine and try to pinpoint the problem.

**Comment by jigish** [comment]
wait, SWOD? really? I don't even think I have a spinning wheel =/

**Comment by robacarp** [comment]
Yep, no problem.  Not much to it yet, heh:

```
# This is the default .slate file.
# If no ~/.slate file exists this is the file that will be used.

config defaultToCurrentScreen true
config nudgePercentOf screenSize
config resizePercentOf screenSize

# Window Hints
bind esc:cmd hint

bind 0:cmd move screenSizeX/2;0 screenSizeX/2;(screenSizeY/9)*7
bind 9:cmd move 0;0 screenSizeX/2;(screenSizeY/9)*7
bind 6:cmd move screenSizeX/4;0 screenSizeX/2;(screenSizeY/9)*7
bind 1:cmd move 0;0 screenSizeX;screenSizeY
bind 2:cmd move 0;0 screenSizeX;screenSizeY*7/9
```

**Comment by robacarp** [comment]
Yea, I can't get it to reproduce though.  I just quit and restarted Slate.  I've opened, resized, closed and skitched the Current Window Info several times...no idea what happened.

Looking in the console, I found something interesting, but I'm not sure if its related: https://gist.github.com/3821838

**Comment by jigish** [comment]
hmm. are you using dvorak by any chance? that is all that I can think of. I just tried your .slate file and it works fine for me :(

**Comment by robacarp** [comment]
oooo, why yes I am.  I didn't even think of that.

**Comment by robacarp** [comment]
Yea, that sorted it.  Man, sorry for just blatantly wasting your time there.

**Comment by jigish** [comment]
No worries! Glad you solved it. Just want to make sure that the way you solved it was with `config keyboardLayout dvorak`.

**Comment by robacarp** [comment]
Yep.  I searched for dvorak in the Readme and was squared away right quick.
