### ISSUE TITLE
Slate does not launch ("weird reason: 13" in the logs)

### ISSUE THREAD

**Issue by brabalan** [jigish/slate#105]
Slate does not launch because of EAccess (unauthorized). Looking at the file installed through the dmg, it seems the application is not executable:

```
/Applications ls -al Slate.app/Contents/MacOS 
total 752
drwxr-xr-x@ 3 schmitta  admin     102 Oct  2 05:33 .
drwxr-xr-x@ 7 schmitta  admin     238 Oct  2 05:33 ..
-rw-r--r--@ 1 schmitta  admin  383276 Oct  2 05:33 Slate
```

Doing a "chmod a+x" on the Slate binary solves this issue. Is this a packaging problem?

**Comment by jigish** [comment]
Ugh. I keep forgetting to make things executable after copying. I'll fix this.

**Comment by jigish** [comment]
Should be fixed now. And in every future version. You should re-download it, though because not only the Slate binary needs to be executable, but the "finish_installation" binary within the Sparkle Framework as well. I've re-uploaded the dmg so if you download it again you should be fine.

**Comment by brabalan** [comment]
Thanks, it's working now.
