### ISSUE TITLE
Ability to center windows on screen / move windows without changing size.

### ISSUE THREAD

**Issue by ThisIsMissEm** [jigish/slate#107]
Hopefully this isn't a case of me reading the documentation wrong, but I'm trying to set up something similar to sizeup's `cmd + alt + ctrl + c`, which centers the current window on the screen. All that I can get working is it centering on one axis.

**Comment by jigish** [comment]
it is a bit complicated but here is what it should look like:

`bind c:ctrl;alt;cmd move screenOriginX+screenSizeX/2-windowSizeX/2;screenOriginY+screenSizeY/2-windowSizeY/2 windowSizeX;windowSizeY`

**Comment by jtbrough** [comment]
I wanted to create a similar binding to center a window and set it to 80% of the screen's hight/width.

```
bind c:ctrl;alt;cmd move screenOriginX+screenSizeX/2-windowSizeX/2;screenOriginY+screenSizeY/2-windowSizeY/2 screenSizeX*.8;screenSizeY*.8
```

It does work, but on first press it doesn't center the screen appropriately. Pressing the binding again seems to resolve the issue, but the behavior is a bit odd.  Maybe there is a better way to accomplish this?

Thanks!

**Comment by almostthor** [comment]
I'm having the same issue as jordantbro. Anyone have any ideas as to why, or if there is a better way to accomplish this goal?

**Comment by almostthor** [comment]
OK, I did a little more thinking about this, and I came up with this solution:

```
bind c:ctrl;alt;cmd move screenOriginX+(screenSizeX/2-(screenSizeX*0.4));screenOriginY+(screenSizeY/2-(screenSizeY*0.4))  screenSizeX*0.8;screenSizeY*0.8
```

This now works every time. I think the issue is that when the command is executed the first time, the windowSizeX and windowSizeY vars are set to the window's size _before_ execution. Thus, when you execute the command it is calculating based on the original size.

Anyway, it seems to work now with doing the calculation relative to the screen size.

**Comment by jtbrough** [comment]
Thanks @almostthor!

I ended up with the following chained command (because I like the ability to toggle between centered and full screen with the same key binding).

```
bind c:ctrl;cmd chain move screenOriginX+(screenSizeX/2-(screenSizeX*0.4));screenOriginY+(screenSizeY/2-(screenSizeY*0.4))  screenSizeX*0.8;screenSizeY*0.8 | ${full}
```

where ${full} is defined as:

```
alias full move screenOriginX;screenOriginY screenSizeX;screenSizeY
```
