### ISSUE TITLE
Document the difference between "up" and "above", "down" and "below", and what is "behind"

### ISSUE THREAD

**Issue by brabalan** [jigish/slate#108]
I'm trying to find some shortcuts to focus between windows, and reading issue #67 was very useful in understanding how "focus left" and "focus right" work. Unfortunately I don't understand the difference between "up"  and "above", and between "down" and "below".

I've also tried using "behind", but cannot make it work. I have two identically windows from the same application stacked one over the other, and I wanted to use "focus behind" to switch between them. Unfortunately I switch to a window from a different application. How is "behind" supposed to work?

**Comment by jigish** [comment]
So up and above are the same thing. above is an alias for up. Same with down and below.

Behind is a bit quirky. It will try to focus a window whose z-index is lower and is behind the current window. A lot of the window selection is based on titles and such so if you have a lot of windows layered on top of each other it won't work very well. I would suggest only using behind when you have two windows on top of each other.
