### ISSUE TITLE
configuration "windowHintsIgnoreHiddenWindows" not taken into account when focusing

### ISSUE THREAD

**Issue by brabalan** [jigish/slate#109]
I have "config windowHintsIgnoreHiddenWindows true" in my .slate file. If I do a "Hide Others" from an application, then move using "focus left" or "focus right", windows from other applications will still be selected, even though they are hidden.

**Comment by jigish** [comment]
Couple of things here
1. `windowHintsIgnoreHiddenWindows` is only for the Window Hints feature. It is meant to ignore windows that are not visible on the screen
2. If your window is hidden, you should not be able to focus to it. I just tried and can replicate what you are saying. I'll fix that.

**Comment by brabalan** [comment]
1. I was confused about the documentation, which says (for focus) "minimized and hidden windows are ignored and a couple global configuration options set using the config directive exist to tweak this". As this is the only option I found about hidden windows, I thought this was it.
2. Great, thanks!

**Comment by jigish** [comment]
Ah, I'll fix my documentation as well to be more clear.

**Comment by jigish** [comment]
Fixed. This will be in the next release (1.0.6)

**Comment by brabalan** [comment]
Thanks a lot, it's working great now.
