### ISSUE TITLE
Is it possible to detach and move tabs in applications?

### ISSUE THREAD

**Issue by jlebrech** [jigish/slate#112]
for example I have sublime text and I want to move from vertical split panes in sublime to a window on each monitor.

or for example move my iterm tabs around

if this isn't possible, would it be possible to create a script that will send a command to sublime for it to detach a tab before slate starts moving them.

**Comment by jigish** [comment]
As part of Issue #85 I'm going to try to add before and after hooks so that you can execute a shell command before/after a slate binding runs. That should make this possible. Moving tabs around would be application-specific so I probably won't add that functionality directly in to slate.

**Comment by jlebrech** [comment]
That's great

**Comment by jigish** [comment]
Tracking the command line stuff in #85, closing this issue.
