### ISSUE TITLE
Google Chrome - piping not working

### ISSUE THREAD

**Issue by 5avage** [jigish/slate#113]
I've tried everything I can think of to make this work:

```
alias lr40      move screenOriginX+screenSizeX/10*6+1;screenOriginY+screenSizeY/2+1   screenSizeX/10*4;screenSizeY/2  ${mon-cinema}
alias 2full     move screenOriginX;screenOriginY  screenSizeX;screenSizeY  ${mon-laptop}

layout code 'Google Chrome' ${lr40} | ${2full}
layout code 'iTerm' ${ur40}
```

All Chrome windows always go to the first piped value, stacked on top of each other. I've verified the aliases independently, and if I change the order the chrome windows all go to the "2full" instead of "lr40".  If I switch iTerm with Chrome, it works correctly with multiple iTerm windows, so it seems particular to Chrome.

**Comment by jigish** [comment]
So Chrome has some issues in that when you try to move/resize the window it moves and resizes but reports that it failed to do so. As a result you need to add the "IGNORE_FAIL" option:

```
alias lr40      move screenOriginX+screenSizeX/10*6+1;screenOriginY+screenSizeY/2+1   screenSizeX/10*4;screenSizeY/2  ${mon-cinema}
alias 2full     move screenOriginX;screenOriginY  screenSizeX;screenSizeY  ${mon-laptop}

layout code 'Google Chrome':IGNORE_FAIL ${lr40} | ${2full}
layout code 'iTerm' ${ur40}
```

**Comment by jigish** [comment]
For the record, Adium has the same issue in case you use it as well.

**Comment by 5avage** [comment]
Awesome, that did the trick, thanks!
