### ISSUE TITLE
keys bound to the same thing have different behavior?

### ISSUE THREAD

**Issue by brabalan** [jigish/slate#116]
I have a very simple .slate file:

```
# Focus bindings

bind right:cmd;alt focus right
bind  left:cmd;alt focus left
bind    up:cmd;alt focus behind
bind  down:cmd;alt focus behind
```

When I do a cmd alt up or cmd alt down, I sometimes get a different behavior. Here is one I found reproducible.

I have two emacs windows on the left hand side of the screen, with the exact same size (620x873), stacked one over the other. I also have a Firefox window almost maximized to the whole screen (1436 x 878). If I put the emacs windows forward (by cmd-tab), doing "cmd-alt-up" switches between the two windows, as expected. However, if I do "cmd-alt-down" I switch to the Firefox window. Then it's not possible to get back to the emacs windows by any combination of "cmd-alt-arrow". This seems a bug for two reasons:
- it's not consistent with the other key binding, which is bound to the same thing
- there is an emacs window behind, so it should be preferred.

I have also found some other strange behavior:
- switch from Emacs to Firefox (cmd-tab), then
  - cmd-alt-up brings back the emacs window (so switching with cmd-tab is different than switching focus)
  - cmd-alt-down brings the emacs window forward then immediately sends it back, leaving the Firefox window with the focus. This can only be done once after a cmd-tab.

**Comment by jigish** [comment]
Hmm. That interesting. I'll admit that "focus behind" is a bit quirky right now but this sounds really weird. I'll take a look.

**Comment by brabalan** [comment]
I'm very sorry, but this was a bug from my side. I had a Keyboard Maestro shortcut to hide applications that was triggered instead of the slate shortcut. Sorry for the confusion.
