### ISSUE TITLE
Focus application

### ISSUE THREAD

**Issue by fechu** [jigish/slate#117]
I would really like to see an option to use `focus` also with an AppName. It should work in a way the frontmost window of the application is focused. 

I would try to implement it if that knows the project could guide me where I have to start looking.

**Comment by jigish** [comment]
This was actually really simple and I had some time today so I implemented it. It will be in the next version (1.0.7) when I release it.

**Comment by fechu** [comment]
That's great and really fast!

**Comment by fechu** [comment]
Hey jigish, 
I just tried it out and it works as expected with a `bind` operation. But I cant get it to work in a `layout` operation. I define a layout and bind it to a keystroke. It just resizes the application but doesn't focus it. 

`layout surf   'Safari'    throw 1 resize | focus 'Safari'`

**Comment by jigish** [comment]
So there are actually a couple ways you can achieve what I think you are trying to do. `layout` works with operations that move or do things to a particular window and not with things like focus. Here are the couple of options you have:
1. use a `sequence` for a one-off case where you want to just focus one app on one layout.

```
layout surf 'Safari' throw 1 resize
bind 1:ctrl sequence layout surf | focus 'Safari'
```
1. use `layoutFocusOnActivate` if you always want to focus things after any layout activates

```
config layoutFocusOnActivate
layout surf 'Safari' throw 1 resize
bind 1:ctrl sequence layout surf
```

If neither of this hit your use case let me know and we can discuss how to add something that will.
