### ISSUE TITLE
Ability to "Hide" Applications

### ISSUE THREAD

**Issue by aonic** [jigish/slate#118]
This might be considered a workaround for #78 but even as a stand alone feature it would be a good idea. Being able to configure windows to be CMD+H (Hidden) from view.

A use case for this would be hiding terminal, text editors, and other development tools from view when just browsing the web or watching videos, or hiding side project windows and apps from view and un-hiding work related project windows when at work.

There is a way to do it in AppleScript:

```
tell application "System Events" to set visible of process "AppName" to false
```

**Comment by jigish** [comment]
This is done. I've added the ability to hide, show, and toggle a list of applications.

**Comment by aonic** [comment]
That was amazingly fast. Thanks!

**Comment by aaronlifton3** [comment]
Can you retrive the currently running list of applications as a list and make it a variables?
e.g. 
    `hide allappsblah > show 'Chrome'`

**Comment by jigish** [comment]
I've added a couple things. First I added the ability to do something like `show all`. Unfortunately `hide all` doesn't work as you would think because OS X does not allow every single window to be hidden. It will auto-show one of the hidden windows. So to cater to the case that you list, you can do the following:

```
hide all-but:'Google Chrome'
```

This will be available in 1.0.9

**Comment by jigish** [comment]
1.0.9 is pushed.

**Comment by aaronlifton3** [comment]
holy shit, that was fast. definitely a useful feature. thanks for listening to the users, respect. this app is quality, i'll try to contribute to it.

**Comment by aonic** [comment]
Not sure if this is intentional or not, but I couldn't get the hide/show operation to work with layouts. Not a deal breaker, just thought I'd mention in case it was a bug

**Comment by jigish** [comment]
Ah yah I need to update the readme to be more clear. Layout cannot work with anything that does not apply to a single window. It is meant only for move related operations. If you want to tie hide/show in with layouts:

```
layout bestLayoutEver 'iTerm' move screenOriginX;screenOriginY screenSizeX;screenSizeY
bind 1:ctrl sequence show 'iTerm' | layout bestLayoutEver | hide all-but:'iTerm'
```
