### ISSUE TITLE
using fn as a modal key defuct

### ISSUE THREAD

**Issue by seletz** [jigish/slate#120]
Hi, first I **love** slate.  And I'm mostly living in terminal and MacVim, and thus #100 is
right for me.

However, I seem to be unable to use `fn` as a modal-key.  Am I missing something?

**Comment by jigish** [comment]
Interesting. it seems as though fn is reserved as a modifier in OS X. I'll have to remove it from Allowed Keys. Unfortunately this means unless I jump through hoops that I really don't want to I won't be able to allow it for use as a modal-key =/. Sorry!

**Comment by jigish** [comment]
I've created Issue #120 to at least enable fn as a modifier key

**Comment by seletz** [comment]
Thanks!  But I think you mean #121 ;)
