### ISSUE TITLE
Enable fn as modifier key

### ISSUE THREAD

**Issue by jigish** [jigish/slate#121]
do it

**Comment by jigish** [comment]
This is implemented and will be in version 1.0.12

**Comment by tzarskyz** [comment]
Hmm, updated to version 1.0.12 and "fn" is still not being recognized as a modifer in bindings. Maybe it is not fully implemented yet or my settings are wrong? Again, thank you so much for your work on Slate. It has become an indispensable tool. I can finally ditch windowkeys when fn works for moving windows. If it helps here is an example of how I have fn setup… pretty much ripped right from the default .slate file…

# Nudge Bindings

bind right:fn nudge +10% +0
bind left:fn    nudge -10% +0
bind up:fn    nudge +0   -10%
bind down:fn  nudge +0   +10%

Thanks for your help… again. Cheers bud!

**Comment by jigish** [comment]
O man it looks like for some reason Apple is not firing things correctly when using function with arrows. Either that or OS X is eating the event. Using function with other keys works just fine. I'll look in to this more but it seems like there may not be much that I can do about it.

**Comment by tzarskyz** [comment]
Okay thanks for getting back to me, I will try it with other keys in the meantime. I don't want to say it "has" to be possible but the previous app I used before discovering Slate was "WindowKeys" and it allows function with arrow keys. I have no programming knowledge so I can't really say much on it but the developer is actually a pretty nice guy and it might be worth asking him if you get stuck on solving it. I realize you have plenty of other additions and features you want to add so if this gets put on the back burner I completely understand. I still very much appreciate you getting the function key to work with other keys. Thank you again for the quick response.

**Comment by SethMilliken** [comment]
FWIW, I'm pretty sure `fn` + arrow keys generate `Home`, `End`, `PgUp`, `PgDown` by default.

**Comment by tzarskyz** [comment]
FWIW, you solved my problem! Many thanks for chiming in.

**Comment by wmayner** [comment]
I'm having trouble using `fn` as a modifier in conjunction with `alt`, `ctrl`, and `cmd` all at once:

```
bind i:ctrl,alt,cmd,fn ${1-main}   
```

doesn't seem to work for me. Apologies if I'm doing something wrong; just started using it and still getting used to it. Thanks for making such an awesome app!

**Comment by dangelov** [comment]
Not sure if anyone else is having this issue, but here's what happens to me:
`bind r:fn nudge +10% +0`
seems to bind it only to "r". So me trying to type "trying" would move the window to the right and eat the r.

**Comment by jigish** [comment]
hmm. what version of slate are you running @dangelov? and what OS version? It seems to be working fine for me on the latest slate and Lion.

**Comment by dangelov** [comment]
I'm running the latest version of Slate and Mountain Lion - let me know if you'd like more details or if you'd like me to test a build.

**Comment by kizzx2** [comment]
For the record I seem to experience the same problem as @dangelov. I have

```
S.bind("1:fn", myOp);
```

It seems to bind _just_ `1`

## 

BTW great work with Slate! Thanks so much!

**Comment by dreki** [comment]
Thanks to direction from @SethMilliken (and the work by @jigish of course!) this config works for me:

```
# Resize Bindings (Using fn Key)
bind end:alt             resize +10% +0
bind home:alt            resize -10% +0
bind pageUp:alt          resize +0   -10%
bind pageDown:alt        resize +0   +10%
bind end:ctrl;alt        resize -10% +0 bottom-right
bind home:ctrl;alt       resize +10% +0 bottom-right
bind pageUp:ctrl;alt     resize +0   +10% bottom-right
bind pageDown:ctrl;alt   resize +0   -10% bottom-right
```
