### ISSUE TITLE
Ability to select all windows except frontmost

### ISSUE THREAD

**Issue by constantin3000** [jigish/slate#122]
I tried to do a layout for the finder, where i could move the frontmost window into the upper left corner and arrange the rest in a stack with only the titlebar visible in the lower left half of the screen. For that it would be practical if you would have the possibility to select a certain option not only by the number of windows (first one, second one...) but to have a certain option only applied to the first window and another to the rest (a counter variable could be practical too, to know how many windows there are and which window is to change). 

For me something like this results in looping between option-1 and 2 for the remaining windows
layout laptop 'Finder':MAIN_FIRST:REPEAT  ${option-1} | ${option-2} 

as a workaround I made unique options for the first 10 windows, it works but it is not very elegant
layout laptop 'Finder':MAIN_FIRST                          ${top-right} | ${option-1} | ${option-2} | ${option-3} | ...

for me that would be a very useful addition to the already awesome program, I don't want to miss anymore.

**Comment by jigish** [comment]
Hmm. Sounds fun to implement lol. I'll think of something.

Here is what I'm thinking so far:
- add some sort of option to `REPEAT` so it can be like `REPEAT[start,end]` where start is the start index of the repeat and end is the end index of the repeat
- add an auto-alias for layouts like `${layoutWindowNumber}` that will be replaced with the current window iteration number before each individual operation is run

**Comment by constantin3000** [comment]
Yes sounds good, something like this should work. Maybe also with the ability to say e.g.
REPEAT[1,-1] to let it repeat that option from the second to the last window

**Comment by brabalan** [comment]
I hesitated before creating a new issue, but as this is very related to this one, I'll comment here instead.

Edit, short summary: make "all-but" work with move commands inside layout directives.

I would really like the ability to specify a layout for "every window except the ones from this application". My setup is like this: two emacs windows on the left, side by side, and every other windows on the right, of the same size (only the frontmost being visible). At the moment, when I encounter a window that does not have the correct size, I resize it using a shortcut. Being able to resize all of them through a layout directive would be quite useful.

**Comment by jigish** [comment]
With [JavaScript Configs](https://github.com/jigish/slate/wiki/JavaScript-Configs) this (and many other things) is now possible without using weird options. You can create a free-form operation (a javascript function) to do whatever you want. Check you [this page](https://github.com/jigish/slate/wiki/Layouts) for an example.

**Comment by jigish** [comment]
In particular on the [Layouts](https://github.com/jigish/slate/wiki/Layouts) page, the Google Chrome part of the layout shows a free form operation.
