### ISSUE TITLE
Hints font configuration

### ISSUE THREAD

**Issue by arlobryer** [jigish/slate#126]
Hi,

Firstly, amazing app. Complete game changer.

I just updated to 1.0.10 to get the hints icons which is a cool feature. However it seems that I can't change the overlayed font properties anymore (color/size). Am I missing something?

Thanks.

**Comment by arlobryer** [comment]
OK I explored this a bit more. It seems that the font properties are only changed upon restarting the application rather than when selecting 'Load Config' from the menu.

**Comment by jigish** [comment]
Yah the Load Config option is sort of "use at your own risk". I need to add that clarification in the readme. There are a bunch of things that are not re-initialized when you Load Config.

**Comment by arlobryer** [comment]
OK, thanks.
