### ISSUE TITLE
Modal command isn't configuring properly.

### ISSUE THREAD

**Issue by robacarp** [jigish/slate#127]
I can't really sort out if I'm doing something wrong in configuring things or if I'm actually onto the scent of a bug.

I'm on 1.0.10, I just upgraded this morning to verify its still doing this.

In my .slate, I have this:

`bind 5:f6 move screenSizeX/3;screenSizeY*7/9 screenSizeX/3;screenSizeY*2/9`

When I hit that key combination, the targeted window should move to 848,1080 with a size of 852,315.  Instead, it moved to: -4,0 with a size of 900,900.

If instead I change it to a chorded command, as so:

`bind 5:cmd move screenSizeX/3;screenSizeY*7/9 screenSizeX/3;screenSizeY*2/9`

It has the expected behavior.

My .slate file in its entirety is posted [in my config_files repo](http://github.com/robacarp/config_files).

**Comment by jigish** [comment]
Smells like a bug to me. I'll take a look. As a side note in most cases you're going to want to add in `screenOriginX` and `screenOriginY` to the origin coordinates to make sure it is put onto the right screen.

**Comment by jigish** [comment]
Hmm. Ok I can't exactly repro what is happening but from what I can tell it definitely seems like it is because you are not using `screenOriginX` and `screenOriginY`. Here is what I think the bindings should look like:

```
bind 5:f6 move screenOriginX+screenSizeX/3;screenOriginY+screenSizeY*7/9 screenSizeX/3;screenSizeY*2/9
```

`screenOriginX` and `screenOriginY` are the origin coordinates of the current screen. if you don't specify them it will just start at `0,0` which is the top-left of the monitor with your menu bar.

**Comment by robacarp** [comment]
Welll... that didn't work.  Perhaps something is confused because I'm using dvorak?

I copied and pasted that command into my .slate, loaded config, and it sends windows to the top-left @ 900x900 still.

In my current case, I really only position windows on my primary monitor.  My second screen has a terminal on it, but it is always full screen.  Positioning from 0,0 is what I want, implicit or explicit.

The other commands work just fine with or without the origin specification.

**Comment by robacarp** [comment]
I've just stumbled onto another symptom.  I noticed that if I changed the command you provided above to begin with `bind  v:f6 move...` the window moves to a different spot and size, but still not the correct place.  This time it moves to bottom-right of primary screen and becomes ~640x315.

Then, and this is where the magic happened, I did f6 then 5 (which wasn't mapped to anything at all) and the window went back up to top left, 900x900.

Delete the v:f6 binding, reload config, window still goes to bottom right, 640x315.
Quit Sate, restart, v:f6 and 5:f6 mystery bindings go away.

I _think_ this is might be caused by the mappings not getting wiped on config reload (starting with a clean _slate,_ heh).

**Edit:** and now, since I expunged the corrupted map for 5:f6, the mapping as given in my .slate file works fine, with or without the screenOriginX/Y.  :-)

**Edit Again:** this is definitely a map corruption thing.  When rewriting the same chorded map, reloading slate does no good, but quitting and relaunching slate gives me a map with the revisions.

**Comment by jigish** [comment]
ok so I really need to document the fact that Load Config is unstable lol. It doesn't do a full reload, but is useful when slightly tweaking existing bindings.

Aside from that, let me see if I understand correctly:
1. You are using dvorak (I'm assuming you're also using the config to enable dvorak right?)
2. modal binding doesn't work but normal binding does
3. screenOriginX did _not_ fix the problem
4. two different modal bindings with the same operation do different things

Does that sum it up?

**Comment by robacarp** [comment]
Eh, mostly.

Given your comment that Load Config isn't considered stable code, then I wouldn't worry about it.
1. I am using dvorak, and it is configured as such in .slate
2. I only have modal bindings mapped, and they work fine when I quit + reopen slate.  As far as regular mappings, I have no test background.
3. changing the mappings to include screenOriginX did not alter the behavior whatsoever.  All of my window placements happen on the primary screen.
4. the only time I observed two modal bindings doing anything similar was when slate needed to be restarted.

**Comment by jigish** [comment]
Ah so this is a Load Config issue then. Thats good because #131 is done and will be in the next version. It will fix Load Config by completely reloading Slate when you use that option. Closing this issue.
