### ISSUE TITLE
Launch process or new window

### ISSUE THREAD

**Issue by arlobryer** [jigish/slate#128]
Is there an argument for allowing new processes (or windows of a current process/app) to be set to launch from the config file?
This would allow e.g. resizing iTerm to half the screen and have a new iTerm (or other) window launch in the other half with a single binding.

**Comment by SethMilliken** [comment]
FYI, @jigish discusses adding an operation for running shell commands [here](https://github.com/jigish/slate/issues/78#issuecomment-9121185) and [here](https://github.com/jigish/slate/issues/85).

**Comment by arlobryer** [comment]
Thanks. I was under the impression that that feature would be to access slate functionality from the cli, although of course if this would also mean slate had a hook to run shell commands that could be used to launch/close programs.

**Comment by jigish** [comment]
@arlobryer - The idea would be to do both. something like

`bind 1:ctrl shell somthing`

as well as

`$ slate activate 1:ctrl`

**Comment by arlobryer** [comment]
OK. Thanks for the clarification.
