### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by schnittchen** [jigish/slate#129]
It says there'a new version available, lets me choose "Install Update", downloads, unpacks, lets me hit "Install and Relaunch" and then hangs forever on "Installing update...".

I tried to build from source but failed.

I should mention I'm still running on 10.6.

**Comment by jigish** [comment]
Can you do me a favor and do this:

```
ls -al /Applications/Slate.app/Contents/Frameworks/Sparkle.framework/
ls -al /Applications/Slate.app/Contents/Frameworks/Sparkle.framework/Resources/finish_installation.app/Contents/MacOS/
```

It is likely the binary for the installation is not executable. Also, which version of Slate are you using?

**Comment by schnittchen** [comment]
Hmm. I'm up-to-date now. So one of the things I tried worked.

I'll close this bug and re-open it when it happens again.
