### ISSUE TITLE
Provide a bindable operation for reloading the slate config

### ISSUE THREAD

**Issue by purcell** [jigish/slate#131]
It would be nice to be able to say

```
bind r:ctrl;alt;cmd reload
```

in order to make Slate reload its config, rather than having to locate and click the menu item.

Having this functionality would also go some way towards relieving the inconvenience described in #130.

Really enjoying Slate so far; I'd been a happy Moom user, and it has been a pretty smooth transition.

**Comment by jigish** [comment]
So the reason why I don't want to do this is because the "Load Config" option in the menu bar is _not_ perfect in any way. Because of the way things are bound it is kind of difficult to clear state and I haven't coded it up yet. As such I won't do this unless Load Config is clean.

**Comment by purcell** [comment]
But if I click "Load Config" in the menu, is that any safer than triggering it via a binding?

**Comment by jigish** [comment]
Definitely not, but that doesn't mean it is a good idea :). I feel like if I make it a binding then people will end up using it more and more when it really isn't meant to be used that much at all. If you want to properly reload your config you should really just restart Slate. Load Config really is just meant to update if you change something slightly inside of a binding that already exists.

**Comment by purcell** [comment]
Aha, I see. How about a `relaunch` operation, then? ;-)

**Comment by jigish** [comment]
That I can do :)

**Comment by purcell** [comment]
LOL, great!

**Comment by jigish** [comment]
Ok. I've changed the "Load Config" to "Relaunch and Load Config". I've also added a relaunch operation. This will be available in the next version (1.0.11)

**Comment by purcell** [comment]
Awesome - thanks!

**Comment by jtbrough** [comment]
Relaunch and Load Config is great, but for my use case a configurable boolean for relaunchConfigOnSave would be ideal.
