### ISSUE TITLE
Is the function (fn) key usable as a modifier? Thought so, but can't seem to get it to work…

### ISSUE THREAD

**Issue by tzarskyz** [jigish/slate#134]
First of all thank you for creating this app and making the source available. Although I can't do much with the source it is still amazing and generous. I'd love to donate so if you have a donate button I missed somewhere please point me in that direction.

As for my question… I saw the list of available keys and saw "f" before f1, f2, etc… so I was thinking that might stand for the function key "fn" but I can't get it to work as a modifier. If it currently does not work as a modifier are there plans to implement it, would be great especially on my laptop keyboard where so many of my modifier key combos + arrow keys are tied to other items.

Again, thank you for your time on this project, it is nothing but amazing for a 1.0 release and once I get the hang of configuring everything it will be an essential install on every machine of mine. Sorry if this has been answered but I only saw a thread relating to the function key as a modal key and I need to do a bit more digging to fully understand what that is. Just discovered the app last night and am not very tech savvy.

**Comment by jigish** [comment]
Thanks for the kind words :).

So f1, f2, f3 and such are the keys above the number keys on most keyboards. Issue #120 is tracking the ability to use fn as a modifier key but I'm not 100% sure if it is even possible.

**Comment by tzarskyz** [comment]
thanks for pointing me to the issue about using the function key as a modifier, that would be amazing if possible. I know apps like "WindowKeys" are able to use the "fn" key + arrows to move windows so it must be possible somehow. By the way, is there no way to donate and support development? If so please let me know! Cheers and thanks again for the best open source app I have seen in ages.
