### ISSUE TITLE
Binding options

### ISSUE THREAD

**Issue by arlobryer** [jigish/slate#136]
Hi,

It might be nice to be able to select which option to use from a key binding. For example, when resizing it would be nice to be able to select which anchor to use:

anchor = (optional) which corner to anchor on top-left|top-right|bottom-left|bottom-right (default is top-left)

by pressing e.g. ctrl+u (top-left), ctrl+o (top-right) etc.

and then being able to use the previously set resize commands. 

This avoids having to set new bindings for resizing from different anchors.

Similar ideas could be applied to other options.

**Comment by arlobryer** [comment]
Actually better still might be the option to switch between anchors (or other options) with a binding. So in this case you'd be able to switch between anchors with 'ctrl+u', similar to the 'chain' operation.

**Comment by jigish** [comment]
Hey,

I totally understand your point but I am wondering why simply creating two bindings doesn't solve the problem? Implementing the ability to bind multiple keys within a single bind directive is actually completely against my current architecture and could take a lot of effort to implement. If you can use multiple bindings to achieve the same effect I think it would be better to just use that then spend a bunch of time implementing another way of doing it.

**Comment by arlobryer** [comment]
Hi,

Ah, didn't realise it contradicted the design so far. I guess I was imagining it would add flexibility by letting you 'multiply out' the commands as it were (say 4 option commands and 4 resize commands for a total of 16 resize possibilities). I think I was imagining that the chain operation could be adapted to this purpose. 
Assigning separate bindings totally works too though and is the solution I'm using at the moment.

**Comment by jigish** [comment]
hmm. I do see your point. I'm going to close this issue, but I'll keep this idea in mind for when I revamp how the config file looks.
