### ISSUE TITLE
Move doesn't use the current screen

### ISSUE THREAD

**Issue by al3xandru** [jigish/slate#138]
The following binding:

`bind f:cmd;alt;shift        move 0;0 screenSizeX;screenSizeY`

doesn't use the current screen. Tried it with both  `defaultToCurrentScreen` set to true or false.

Slate: 1.0.12
Mac OS X 10.8.2

**Comment by jigish** [comment]
Couple things:
1. `defaultToCurrentScreen` should be `true`
2. Instead of `0;0` it should be `screenOriginX;screenOriginY`

If that doesn't work please send me your `.slate` file and I can look at it.

**Comment by jigish** [comment]
is this still an issue or can I close this?
