### ISSUE TITLE
screenOrigin[XY] with hidden menu bars

### ISSUE THREAD

**Issue by anonfunc** [jigish/slate#147]
When using `move screenOriginX;screenOriginY screenSizeX;screenSizeY` with a hidden menu bar (as enabled with [MenuAndDockless](http://createlivelove.com/79/menuanddockless-20/) or [MenuBarHider](https://github.com/Crazor/MenuBarHider)), there is a small strip of unused space at the very top of the screen where the menu bar would live.  

Ideally, there would be a config option to use the whole screen.

**Comment by paddykontschak** [comment]
`screenOrigin` is accounting for the menubar. `screenSize` however does not. Just change your configuration to `move screenSizeX;screenSizeY screenSizeX;screenSizeY` and you have the whole screen available.

**Comment by anonfunc** [comment]
`move screenSizeX;screenSizeY screenSizeX;screenSizeY` puts the window at the bottom of the screen. (Ironically, it sticks up about the height of the menu bar, otherwise I would have been very confused.)

`move screenSizeX;0 screenSizeX;screenSizeY` works for me, but only because my monitors are in a line from left to right and the same resolution.  That is sufficient for my use case, however.
