### ISSUE TITLE
Variable containing previous position

### ISSUE THREAD

**Issue by eproxus** [jigish/slate#153]
I'd like to have access to `windowLastSizeX` or similar (for all values) which would always contain any previous value from the last slate operation (that is, excluding a manual move of the window for example) so that "on / off" like functionality could be implemented.

For example, if you want `Cmd+Alt+Up` issue a vertical resize to 100% of the screen, it would be nice if `Cmd+Alt+Up` could issue a resize back to the last size.

Suggested variables should include at least:
- `windowLastTopLeftX`
- `windowLastTopLeftY`
- `windowLastSizeX`
- `windowLastSizeY`

They should all be the last recorded value of their normal counterpart before the last Slate operation (or chain).

**Comment by jigish** [comment]
Hmm. I'm getting a good amount of requests for a feature like this. somehow or another I'll implement a way to do this - whether it be an "undo" or something like this or both.

**Comment by jigish** [comment]
So I've implemented the undo operation if that helps. I'll look into adding this as well. For reference: Issue #165

**Comment by eproxus** [comment]
Will check out undo. Does it work in the case of `resize` -> `focus left` -> `focus right` -> `undo`, for example?

I guess these variables are something akin to a window local undo stack.

**Comment by jigish** [comment]
So now that [JavaScript Configs](https://github.com/jigish/slate/wiki/JavaScript-Configs) exist, if you are comfortable with Javascript, this can be solved by simply storing values of the window's size into variables in JavaScript before executing an operation. Will that solve your use case?

**Comment by eproxus** [comment]
@jigish So, is there a permanent JavaScript scope that stays alive between calls to the shortcuts then?

**Comment by calvinwyoung** [comment]
Sorry to resurrect a closed issue, but I'd really like to implement something in JS to make this work.  The problem I'm running into is that I can't reliably distinguish between multiple windows of the same application.  I can't use `window.pid()` since that returns the ID of the application, and I can't use `window.title()` because that's likely to change.

Did you end up figuring out a solution?

**Comment by eproxus** [comment]
Hey, missed your reply. No, I haven't had time to implement something in JS for this. Work came in between.

How about PID + title + current position + current size (which would then have to be updated on every resize and move)? This would not work for windows in the same app existing exactly on top of each other, but would otherwise work.

**Comment by calvinwyoung** [comment]
Yeah I guess something like that makes sense and should work for now.  Hopefully we'll have something a little more robust in the future :)
