### ISSUE TITLE
`fn` doesn't seem to work at all

### ISSUE THREAD

**Issue by michaelmior** [jigish/slate#156]
My `~/.slate` looks like this. 2011 MacBook Pro with OS X 10.7.5 if that matters. Any help would be appreciated :)

```
alias full move screenOriginX;screenOriginY screenSizeX;screenSizeY
alias lefthalf move screenOriginX;screenOriginY screenSizeX/2;screenSizeY
alias righthalf move screenOriginX+screenSizeX/2;screenOriginY screenSizeX/2;screenSizeY
alias topleft corner top-left resize:screenSizeX/2;screenSizeY/2
alias topright corner top-right resize:screenSizeX/2;screenSizeY/2
alias bottomleft corner bottom-left resize:screenSizeX/2;screenSizeY/2
alias bottomright corner bottom-right resize:screenSizeX/2;screenSizeY/2

bind q;fn ${topleft}
bind e;fn ${topright}
bind a;fn ${lefthalf}
bind d;fn ${righthalf}
bind z;fn ${bottomleft}
bind c;fn ${bottomright}
```

**Comment by leemarrett** [comment]
Also not working for me; would be great to have fn as an extra modifier.

**Comment by jigish** [comment]
This is probably because your syntax is a tad off:

`;` should be `:`

```
bind q:fn ${topleft}
bind e:fn ${topright}
bind a:fn ${lefthalf}
bind d:fn ${righthalf}
bind z:fn ${bottomleft}
bind c:fn ${bottomright}
```

Let me know if this doesn't work.

**Comment by leemarrett** [comment]
Nope, this doesn't work either.

bind right:fn          resize +1% +0

Just ignores the fn and binds the resize to the right arrow.

**Comment by jigish** [comment]
please see issue #121. Other uses were having similar problems with the fn+arrow keys. I've listed in the readme that it doesn't work but people seem to have found that it doesn't because that keystroke is by default bound to something in OS X. Maybe that is your issue?

**Comment by leemarrett** [comment]
Should it work for right:alt;fn ? or r:fn;shift?

If I make:

bind r:fn;shift          resize +1% +0

The resize ignores the fn and just works with shift+r.

Mountain Lion(10.8.2), Slate 1.012

**Comment by jigish** [comment]
Interesting. I have not tried the `fn` key on Mountain Lion yet myself. I'll try to do it tonight and see what happens. It may be a Mountain Lion specific problem.

**Comment by michaelmior** [comment]
@jigish Sorry for the delay in responding here. Your initial comment about the syntax has now caused the shortcut to be recognized, but now the fn modifier is ignored completely. This is not just with arrow keys for me.

**Comment by kjhealy** [comment]
I'm having this issue as well on Mountain Lion. The fn key modifier is ignored. E.g. with this config, 

```
bind q:fn ${leftmost}
bind w:fn push top bar-resize:screenSizeY/2
bind e:fn ${rightmost}
```

The actions are activated just by pressing 'q', 'w', or 'e'.

**Comment by ravasthi** [comment]
I'm also having this issue on ML:

```
alias full move screenOriginX;screenOriginY screenSizeX;screenSizeY
bind 1:fn ${full}
```

This mapped my 1 key instead.

**Comment by jigish** [comment]
interesting. leave it to apple to ninja-change the function modifier constant in mountain lion. I'll test tonight to see what it is and try to fix it.

**Comment by jigish** [comment]
wow. big fat ugly fail. I just checked this out on my mountain lion laptop and it seems like mountain lion ninja removed the ability to bind the `fn` key. there really isn't much i can do =/. i could try quartz event taps but that is going to be super irritating and based on my experience with the `switch` operation they are not reliable. i'm going to close this unfortunately and remove `fn` from the modifiers list.

**Comment by ravasthi** [comment]
Thanks for checking this out so quickly, Jigish.

**Comment by ghost** [comment]
FWIW, using KeyRemap4MacBook allows one to remap the Fn+<key> or Fn + <other modifiers> + key type shortcuts quite reliably. Even on Mountain Lion. Which means that it should be possible, in theory, for Slate to be able to allow Fn based based bindings as well.

Edit:
Allowing Fn as a modifier (with all the combinations possible by combining it with other modifiers) would make it really convenient to create shortcuts that won't conflict with system shortcuts or those of other applications.

**Comment by newduke** [comment]
Please fix!
