### ISSUE TITLE
ASCIIToCode_Dvorak.plist logic?

### ISSUE THREAD

**Issue by Goles** [jigish/slate#157]
Hello,

I want to contribute a new keyboard layout, but I can't wrap my head around the logic of  `ASCIIToCode.plist` and `ASCIIToCode_Dvorak.plist`.

Could someone explain me what this files are about?

Thanks.

**Comment by jigish** [comment]
Basically these files are a mapping of key name (to use in the .slate file) to key code. you can get key codes using this handy application: http://manytricks.com/keycodes/

Adding a new layout would consist of adding a new .plist, then changing `Binding.m`'s method `asciiToCodeDict` do add the new layout. You'd also have to add a new keyboard layout string constant as well (e.g. `KEYBOARD_LAYOUT_DVORAK`).

**Comment by Goles** [comment]
Thanks, a pull request was sent before I could submit it myself... shows that this project is moving fast :+1:
