### ISSUE TITLE
Nice way to edit slate config files with ST2 - ST2Slate package by kvs.

### ISSUE THREAD

**Issue by tzarskyz** [jigish/slate#164]
Check out kvs's st2 package, available through package control as well: https://github.com/kvs/ST2Slate

It's a pretty useful package that imo should be added to the readme so others can use it since many os x users are switching to st2 as of late.

It has some nice snippets and will make your slate config file(s) be recognized as syntax "Slate" - Everything works great out of the box but if your slate config files are not being recognized, define the file name in the slate.tmlanguage file. Just make a new array under the <key>fileTypes</key> and enjoy.

I have no affiliation to the developer or package. Found it useful so thought it should be on the readme, but that is not my call. I just love slate and anything which makes working with slate easier! Thanks jigish for slate and kvs for the package!

**Comment by jigish** [comment]
@kvs - good shit. I'll add this to the read me today.

**Comment by jigish** [comment]
anyone else out there want to make a vim syntax as well? :)

**Comment by jigish** [comment]
done in c3dbe7556560961f16568086e0feeda49be04773
