### ISSUE TITLE
hint now working with colemak keyboard layout

### ISSUE THREAD

**Issue by Goles** [jigish/slate#170]
I tried this in my .slate

```
keyboardLayout colemak
bind 4:ctrl hint ARSTNEIO
```

When I press Control-4 the characters are properly placed over my windows, but I have to press the keys on the qwerty positions to make slate to select the proper window.

I tried restarting slate, but didn't fix the issue.

Any idea of what could be going on here?

**Comment by jigish** [comment]
This is probably because you're missing the 'config' before 'keyboardLayout'. It should look like:

```
config keyboardLayout colemak
```

Let me know if that doesn't work.

**Comment by Goles** [comment]
All is good.
