### ISSUE TITLE
Allow for bindings to modal keys to be repeated, like a modal mode/state

### ISSUE THREAD

**Issue by michaelolson** [jigish/slate#172]
When I first saw the description of modal keys, I was incorrectly envisioning something like the modal editing modes of vim. What I had hoped was that I could enter a modal state where Slate would then interpret all subsequent commands, until modal mode was exited, as belonging to the associated modal key.  For instance:

```
alias modal t,cmd,shift
bind right:${modal}  nudge +10% +0
bind left:${modal}   nudge -10% +0
bind up:${modal}     nudge +0   -10%
bind down:${modal}   nudge +0   +10%
```

This would allow me to enter modal mode with `cmd+shift+t` and then use arrow keys repeatedly until I pressed `cmd+shift+t` again (or some alternate universal modal escape could be defined, like the `esc` key). I think the long modifier sequences that seem common in the configs I have observed are appropriate for one-off commands, but for repeated commands, such as might be expected with nudging and resizing, a modal mode where single keys can be used repeatedly would be very helpful.

**Comment by ranman** [comment]
+1 for this.

**Comment by tzarskyz** [comment]
+1

**Comment by jigish** [comment]
interesting. if I added this as a config option would that suffice? as in would you want _both_ the current functionality as well as the explicit end to modal mode in the same .slate?

The reason I ask is both may require some awkward syntax in the binding

**Comment by mgax** [comment]
+1. I was considering how to implement this in a Python script, but got suck on registering/deregistering the modal key bindings.

**Comment by michaelolson** [comment]
Both is probably preferable for people who use the existing functionality, but a configuration option to enable this style is a great start, particularly if a modal escape key can be separately configured.  Something like:

```
config persistentModalMode true
```

And either the following, for global escapes:

```
config modalEscapeKey esc
```

Or this style, for local-to-a-modal escapes:

```
bind esc:${modal} exit
```

**Comment by skarfacegc** [comment]
+1

**Comment by dahjelle** [comment]
+1

**Comment by jigish** [comment]
I've finally gotten around to implementing this. Here is how it works:

```
config modalEscapeKey esc
alias modal t,cmd,shift:toggle
bind right:${modal}  nudge +10% +0
bind left:${modal}   nudge -10% +0
bind up:${modal}     nudge +0   -10%
bind down:${modal}   nudge +0   +10%
```

I'll update the readme soon. Basically adding ":toggle" to the end of any modal binding will make that modal binding toggled. You can also do this:

```
config modalEscapeKey esc
alias modal t,cmd,shift:toggle
alias modal-toggle t,cmd,shift:toggle
bind right:${modal}  nudge +10% +0
bind left:${modal}   nudge -10% +0
bind up:${modal-toggle}     nudge +0   -10%
bind down:${modal-toggle}   nudge +0   +10%
```

This will make the right and left bindings exit out of modal mode while the up and down bindings will keep slate in modal mode.

Also, `modalEscapeKey` can be a full key sequence like `esc:ctrl` (obviously any modal stuff in there will be ignored).

This will be in the next release (1.0.19?)

**Comment by michaelolson** [comment]
I tried it out, and it works great.  Thanks!
