### ISSUE TITLE
Moving windows between monitors more efficiently?

### ISSUE THREAD

**Issue by byalextran** [jigish/slate#174]
I'm giving Slate a try coming from Divvy and one thing I miss about Divvy is the ability to double-press a keyboard shortcut to move a window from one monitor to the next. 

For example, I had alt+1 setup to full screen a window, if i press it a second time it would full screen the window on my second monitor. 

From looking at the Slate binding options, I don't see a way to mimic this feature. 

I tried using `repeatOnHoldOps throw next` as a possible alternative, but that didn't appear to work. 

Is it possible to do someting similar with Slate?

**Comment by SethMilliken** [comment]
Have a look at the `chain` operation.

**Comment by byalextran** [comment]
Aha! Looks like that operation is exactly what I'm looking for. Appreciate it. 

Thanks!

**Comment by byalextran** [comment]
So I got this to work sort of, but not as ideal or as generic as I'd like. 

`bind pad4:cmd,alt,ctrl,shift chain push left bar-resize:screenSizeX/2 | throw next resize:screenSizeX/2;screenSizeY`

There are two uses cases that are not currently covered with this command. 

### A user with more than two monitors.

Let's say a user has three monitors. On the third key press in the chain, there are no more commands so Slate loops back to the original command (which is simply to resize the window without moving to the next monitor). So essentially that third key press doesn't do anything since the window is already resized left from the previous throw next command. 

You have to press it again to move to the next command in the chain which actually throws to the next monitor. 

You could work around this by adding another command to the chain repeating the throw next command, but that requires updating the config file depending on how many monitors you have and still runs into the second use case issue...

### You change your mind and want the window on the original monitor.

As mentioned in the previous use case, when you loop the chain command, that first command doesn't do anything. 

So if you want to bring the window back to the original monitor after initiating the chain you have to press it four times (assuming you have just two monitors) instead of three. 
1. Resize left on first monitor. 
2. Resize left on second monitor. 
3. (chain repeats) and resizes left on current monitor (but window is already resized left). 
4. Resize left on first monitor. 

The question then is there a way to work around these two use cases? Primarily the second one?

**Comment by gfreezy** [comment]
hi, you may have a look at my config.

https://gist.github.com/gfreezy/6060661

**Comment by byalextran** [comment]
@gfreezy thanks! that's definitely along the lines of what i was looking for. 

however, after a stint with slate i went back to divvy. love the added features of slate, but when it came down to it, all i really needed was the basics (which divvy does extremely well).
