### ISSUE TITLE
Make text on "Current Window Info" window selectable.

### ISSUE THREAD

**Issue by gimbo** [jigish/slate#176]
I'm trying to copy my screen configuration into another bug report, but I can't select the text in the _Current Window Info_ window.  From [issue 102](https://github.com/jigish/slate/issues/102) I see you meant to do that, so I thought I'd open an issue as a reminder. :-)

**Comment by jigish** [comment]
thanks! I completely forgot about this.

**Comment by jigish** [comment]
lol. apparently it isn't because it is not selectable, it is because I keep rewriting the stats. i'll fix that

**Comment by jigish** [comment]
done. it will now refresh whenever it needs to draw but never less that 5 seconds after it has refreshed.
