### ISSUE TITLE
Can't mix chain and sequence

### ISSUE THREAD

**Issue by gimbo** [jigish/slate#178]
Earlier today I tried to mix `chain` and `sequence` operations and didn't get the behaviour I expected.  I see in the documentation that mixing them seems discouraged - for example, in the chain documentation we have:

```
opAndParamsX = any operation string (except sequence, hint and grid)
```

but I wondered what you thought about lifting this restriction in some way.  So here are some thoughts.

Consider:

```
alias op1 <blah>
alias op2 <blah>
alias op3 <blah>
alias op4 <blah>
alias seq1 sequence op1 | op2
alias seq2 sequence op3 | op4
alias ch1 chain seq1 | seq2
```

To me, this seems an entirely reasonable thing to do, and in an ideal world, this would define `ch1` as a chain whose first invocation fired `seq1`, and whose second fired `seq2`:

```
         chain
         /    \
        /      \
       /        \
      /          \
  sequence     sequence
    / \          / \
   /   \        /   \
  /     \      /     \
op1     op2  op3     op4
```

However, that seems not to happen at the moment; I presume that's because aliases are expanded as strings, so we end up with:

```
alias ch1 chain sequence op1 | op2 | sequence op3 | op4
```

and it's completely unclear/ill-defined which `chain` or `sequence` operations each `|` belongs to.  I don't even know what the actual parse tree is in this case.  Is it just going left-to-right?  If so, then I guess it's equivalent to:

```
alias ch1 chain (sequence op1 | op2 | (sequence op3 | op4))
```

with a one-step chain?  (But this is just a guess, I haven't investigated what's _really_ happening.)

One simple way to get round this would be to just redefine how aliases work so that they're more like function calls than string expansions.  Then my approach above would work, I think. It would have a small performance overhead but I doubt it would be noticeable (?).

To really fix it means getting busy with the parser.  I haven't looked into your implementation, what you're doing with your AST, etc. but some thoughts...

An obvious first step is to introduce parentheses, allowing interpretations other than the default, e.g.:

```
alias ch1 chain (sequence op1 | op2) | (sequence op3 | op4)
```

though I don't know how complicated this would be to implement or what knock-on effects it might have...

To Do It Properly I guess means defining precedence levels, in which case I guess `chain` is lower precedence (since its invocations are separated in time and triggered by humans, whereas `sequence`'s parts all happen one after the other).  Then 

```
chain sequence op1 | op2 | sequence op3 | op4
```

gets parsed as 

```
chain (sequence op1 | op2) | (sequence op3 | op4)
```

by default.  Of course, you'd then probably still want to introduce parentheses so people can write:

```
chain (sequence op1 | op2 | (sequence op3 | op4))
```

if they actually do want that!

Apologies if you've considered (and maybe disregarded) all this already. Slate an awesome piece of software as it is, and I realise this is probably a whole can of worms you've got better things to deal with. But I thought I'd flag it up in case you're interested...

**Comment by mgax** [comment]
This looks like something more easily done in a scripting language, there's an interesting discussion at #91.

**Comment by gimbo** [comment]
Brilliant. I love the idea of farming out the config to an existing language.

**Comment by jigish** [comment]
yah I'll definitely make sure things like this work when we move to ruby/python/lua. It seems more and more issues are dependent on it so as soon as I get a bit more time I'll handle it.

**Comment by jigish** [comment]
You now can do this with [JavaScript Configs](https://github.com/jigish/slate/wiki/JavaScript-Configs)
