### ISSUE TITLE
BEFORE shell not working properly

### ISSUE THREAD

**Issue by mLewisLogic** [jigish/slate#180]
Test config:

```
default 1monitor count:1
default 2monitors count:2

layout 1monitor BEFORE shell path:~/ '/usr/bin/touch /Users/mike/1monitor'
layout 2monitors BEFORE shell path:~/ '/usr/bin/touch /Users/mike/2monitors'
```

Result:
When the monitor is plugged in or unplugged, no file is touched. The shell commands work standalone.

**Comment by jigish** [comment]
Interesting. I've tried the following and they both work:

```
default 1mon count:1
default 2mon count:2
default 3mon count:3

layout 1mon BEFORE shell path:~/ '/usr/bin/touch /Users/jigish/tmp/test/ONE'
layout 2mon BEFORE shell path:~/ '/usr/bin/touch /Users/jigish/tmp/test/TWO'
layout 3mon BEFORE shell path:~/ '/usr/bin/touch /Users/jigish/tmp/test/THREE'
```

```
default 1mon count:1
default 2mon count:2
default 3mon count:3

layout 1mon BEFORE shell path:~/ '/usr/bin/touch tmp/test/ONE'
layout 2mon BEFORE shell path:~/ '/usr/bin/touch tmp/test/TWO'
layout 3mon BEFORE shell path:~/ '/usr/bin/touch tmp/test/THREE'
```

have you tried maybe touching something outside of your home directory? or try specifying a local path like above. And just so I have all the facts, what version of OS X are you running and can I get your entire `.slate`?

**Comment by mLewisLogic** [comment]
OS X 10.8.2
MBP retina + Thunderbolt 27"

full .slate:

```
default 1mon count:1
default 2mon count:2

layout 1mon BEFORE shell path:~/ '/usr/bin/touch 1mon'
layout 2mon BEFORE shell path:~/ '/usr/bin/touch 2mon'

layout 1mon BEFORE shell path:~/ '/usr/bin/osascript change_input.scpt "Dvorak"'
layout 2mon BEFORE shell path:~/ '/usr/bin/osascript change_input.scpt "U.S."'
```

**Comment by jigish** [comment]
ok this may be yet another mountain lion issue. my dev box is lion. I'll have to test with my personal 10.8 laptop when I get a chance =/

**Comment by mLewisLogic** [comment]
Tried it without the osascript lines as well, and it didn't change anything, so not an issue with the full quotes.

**Comment by jigish** [comment]
Wow i accidentally commented on Issue #177, but i've commited and pushed a fix:

found and fixed two issues:
1. without checkDefaultsOnLoad = true, the first (and sometimes second) screen configuration change was going unnoticed by slate
2. your nested quotes were being parsed wrong :)

Just pushed version 1.0.15 which should have the fixes.
