### ISSUE TITLE
Window hints hard to read on light colored icons.

### ISSUE THREAD

**Issue by slavick** [jigish/slate#183]
It would be a great improvement to my overall usage of slate if there could be a way to make the hint letter more noticeable on light colored icons. Here is an example of the problem: ![Screen Shot 2012-12-11 at 12 12 49 PM](https://f.cloud.github.com/assets/410512/6413/dac685de-43be-11e2-9fd3-3f881271b529.png)

Maybe if there could be the same dark colored border that is behind the icon to also be behind the hint letter. That would make it stand out much better. Or maybe have the ability to dim the icon behind the hint letter.

I'm pretty new to slate so I don't know if there is a way to accomplish this already. This is the only issue I've run into with slate after having run it for a couple weeks.

**Comment by jigish** [comment]
I like @josh-'s fix for this. We'll have the option to add a rounded rect under the letter once I merge that in.

**Comment by skarfacegc** [comment]
config windowHintsIconAlpha 0.5 

seems to help with this.

**Comment by sasha-ashpis** [comment]
config windowHintsIconAlpha 0.5
is not in the documentation. Are there other hidden features?
