### ISSUE TITLE
quicksilver / sublimetext command pallet style control

### ISSUE THREAD

**Issue by skarfacegc** [jigish/slate#186]
Rather than having to find many non conflicting keyboard commands it would be really neat to have the ability to define a hotkey that basically does this:

1) hit the hot-key
2) A small (floating or not) input area opens
3) User starts typing the name of a command alias
4) command alias(es) auto expand as the user types
5) user hits enter when the right one is selected
6) action takes place

Keybindings are great for some stuff, but something like
cmd-shift-W devenv enter
to move to my development environment window layout would be much saner than having to remember cmd-shift-option-d

I'd seriously recommend checking out sublime text's command pallet (cmd-shift-p) while in sublime text to see what I'm talking about.

**Comment by trishume** [comment]
This sounds interesting but non-trivial to implement.

**Comment by skarfacegc** [comment]
I guess my main idea is to have some way to interact with slate without having to deal with finding shortcuts that won't interfere with other shortcuts.  Command line control would help here as well.  Really neat software btw.

**Comment by tzarskyz** [comment]
Definitely would be cool, but a lot of work to implement. I like it though, it would free up a lot of bindings but I can't see this ever really happening. Nice idea though. +1

**Comment by skarfacegc** [comment]
Thanks for the feedback
