### ISSUE TITLE
Resizing at the screen border/How does anchor work

### ISSUE THREAD

**Issue by al3xandru** [jigish/slate#199]
I've been switching the settings for the resize, but I'm still confused about how it works and what are the cases when they don't work at all.

```
bind 1:cmd;alt;shift     resize +0 +10% bottom-left
bind 2:cmd;alt;shift     resize +10% +0 bottom-left
bind 3:cmd;alt;shift     resize +0 +10% top-right
bind 4:cmd;alt;shift     resize +10% +0 bottom-right

bind 5:cmd;alt;shift     resize +0 -10% bottom-right
bind 6:cmd;alt;shift     resize -10% +0 bottom-left
bind 7:cmd;alt;shift     resize +0 -10% top-right
bind 8:cmd;alt;shift     resize -10% +0 bottom-right
```
1. Window is on the right side screen border. Resizing on the left side (CMD+ALT+Shift+4) does nothing. But if the window is not connected to the screen margin it works.

There are many similar examples, so I guess I don't really understand how the "anchor" for resize works.

**Comment by loshlee** [comment]
I changed shift to ctrl and CMD+ALT+ctrl+4 worked the way I think you wanted CMD+ALT+Shift+4 to. Maybe there's a system-wide consideration.

Here's an AppleScript that might help simplify managing config files a little. Run it twice to see what it does. The first time it creates a folder in your home folder called "Slate Sets" and puts a backup of your .slate file into that folder. (I don't know how to use the markup at GitHub, but if you copy the entire text of the script, it should compile OK in AppleScript Editor, at least it did for me.)

Next time you run it, it lets you make a choice from whatever files exist in the Slate Sets folder and replaces the .slate file with the one you selected, then relaunches Slate to activate that one.

Even if you cancel changing config files, it makes sure Slate is running from the most recently loaded one.

So if you make changes or add any files to the Slate Sets folder, you can load the new ones quickly, no matter what  the file name is. One of the things it doesn't do yet is to provide the name of the last file you activated.

(The above assumes you're already using a .slate file. If you aren't, it performs the operation of creating one from default settings before it performs either of the actions described above, so you would need to run it 3 times to observe its full functionality.)

---

set default_settings to "# This is the default .slate file.

# If no ~/.slate file exists this is the file that will be used.

config defaultToCurrentScreen true
config nudgePercentOf screenSize
config resizePercentOf screenSize

# Resize Bindings

bind right:alt       resize +10% +0
bind left:alt        resize -10% +0
bind up:alt          resize +0   -10%
bind down:alt        resize +0   +10%
bind right:ctrl;alt  resize -10% +0 bottom-right
bind left:ctrl;alt   resize +10% +0 bottom-right
bind up:ctrl;alt     resize +0   +10% bottom-right
bind down:ctrl;alt   resize +0   -10% bottom-right

# Push Bindings

bind right:ctrl;cmd  push right bar-resize:screenSizeX/3
bind left:ctrl;cmd   push left  bar-resize:screenSizeX/3
bind up:ctrl;cmd     push up    bar-resize:screenSizeY/2
bind down:ctrl;cmd   push down  bar-resize:screenSizeY/2

# Nudge Bindings

bind right:shift;alt nudge +10% +0
bind left:shift;alt  nudge -10% +0
bind up:shift;alt    nudge +0   -10%
bind down:shift;alt  nudge +0   +10%

# Throw Bindings

bind 1:ctrl;alt         throw 0 resize
bind 2:ctrl;alt         throw 1 resize
bind 3:ctrl;alt         throw 2 resize
bind right:ctrl;alt;cmd throw right resize
bind left:ctrl;alt;cmd  throw left  resize
bind up:ctrl;alt;cmd    throw up    resize
bind down:ctrl;alt;cmd  throw down  resize

# Focus Bindings

bind right:cmd    focus right
bind left:cmd     focus left
bind up:cmd       focus up
bind down:cmd     focus down
bind up:cmd;alt   focus behind
bind down:cmd;alt focus behind

# Window Hints

bind esc:cmd hint"

set myHome to ((path to home folder) as string)
set _path to myHome & "Slate sets:"
set targ1 to POSIX path of _path
set targ2 to POSIX path of myHome
set user_dotSlate to (targ2 & ".slate")
try
    set name_target to alias (POSIX file (user_dotSlate)) --file name is already taken at destination if no error occurs.
    try
        set name_target to alias (POSIX file (targ1 & "originaldotslate")) --file name is already taken at destination if no error occurs.
    on error
        my backupdotslate(user_dotSlate, (targ1 & "original.slate"))
    end try

```
set ls to (list folder _path)
set ld to {}
repeat with i in ls
    if i is not in {".DS_Store"} then
        set ld to ld & i
    end if
end repeat
choose from list ld with prompt "Choose Slate configuration to activate:"
if result is false then
    my bounce_Slate()
else
    do shell script "rm" & space & user_dotSlate & ";" & "ditto" & space & (quoted form of targ1) & (quoted form of (result as text)) & space & user_dotSlate
    bounce_Slate()
end if
```

on error
    do shell script ("echo \"" & default_settings & space & "\" > " & space & (user_dotSlate))
end try

on backupdotslate(original_Slate, backup_Target)
    set thesource to (quoted form of (POSIX path of original_Slate))
    do shell script "ditto" & space & thesource & space & quoted form of backup_Target
end backupdotslate

on bounce_Slate()
    tell application "Slate" to activate
    do shell script "sleep 1"
    tell application "Slate" to quit
    do shell script "sleep 1"
    try
        tell application "Slate" to activate
    end try

## end bounce_Slate

**Comment by al3xandru** [comment]
Confirmed... the combination `CMD+ALT+Shift`+4(?) seems to conflict with something else. Switched all my bindings to use Alt+Shift and Cmd+Alt (I don't like using Ctrl as the key is available only on the left side of the keyboard)

**Comment by jigish** [comment]
is this still an issue or can I close this?

**Comment by cfenollosa** [comment]
I confirm that `resize +10% +0 bottom-right` does not work if the window's right edge is on the rightmost limit of the screen. If the window is, say, in the middle of the screen, the keybinding works, so it is not a key mapping issue.

`resize +10% +0 bottom-right` seems to resize on the right + nudge to the left, and as the window is at the right limit of the screen, the whole command fails.
