### ISSUE TITLE
Add options to push

### ISSUE THREAD

**Issue by jigish** [jigish/slate#2]
Ability to specify:
1. style - bar (push and resize to a top/bottom/left/right bar)
2. monitor option?

**Comment by jigish** [comment]
monitor is sort of useless and doesn't fit the idea of a "push". Adding style only. Workaround for monitor is to simply use a "move".

**Comment by jigish** [comment]
Added style option with the following values:

```
none - normal push
center - push to direction and center
bar - push to direction and resize to fill other direction ("push right bar" will push the window to the right and resize it to fit the height of the screen
bar-resize:expression - same as above but will also resize the distance away from pushed edge with "expression"
```

**Comment by supersonicclay** [comment]
In case anyone is looking for how to move to another screen and center, here's what I use:

	bind right:ctrl;alt;cmd move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) right
	bind left:ctrl;alt;cmd  move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) left
	bind up:ctrl;alt;cmd    move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) up
	bind down:ctrl;alt;cmd  move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) down
