### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by mrknmc** [jigish/slate#205]
Wouldn't it be nice to implement conditions?

As in when I press cmd+alt+up and I'm in safari, resize window to 90% but for Sublime Text resize to only 75%. I can image the syntax being something like:
guard 'Safari' push up | 'Sublime Text 2' push down | so on...

**Comment by loshlee** [comment]
Or if an operation such as moving to upper left corner for one window was just performed, invoking the same shortcut for another window would move it to upper right corner, and so on. That's the way Optimal Layout (http://most-advantageous.com/optimal-layout/) works.

**Comment by jigish** [comment]
this is being tracked here: #91
