### ISSUE TITLE
How can I center a window using slate?

### ISSUE THREAD

**Issue by Goles** [jigish/slate#207]
I'm using slate as a replacement for SizeUp, I was wondering how can I make slate to center a window like SizeUp `ctrl+alt+cmd C`

I thought that using the `corner` command would be the best way to achieve this, but when using corner you cannot specify the coordinates for the origin of the window ( you're limited to `top-left` ... right ... etc. )

Any ideas ?

**Comment by jigish** [comment]
should be something like this:

`bind c:ctrl,alt,cmd move screenOriginX+((screenSizeX-windowSizeX)/2);screenOriginY+((screenSizeY-windowSizeY)/2) windowSizeX;windowSizeY`

That will center the window on the current screen.

**Comment by supersonicclay** [comment]
Slight optimization if you're using this to move and center on another (potentially smaller screen):

	bind right:ctrl;alt;cmd move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) right
	bind left:ctrl;alt;cmd  move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) left
	bind up:ctrl;alt;cmd    move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) up
	bind down:ctrl;alt;cmd  move screenOriginX+((screenSizeX-min({screenSizeX,windowSizeX}))/2);screenOriginY+((screenSizeY-min({screenSizeY,windowSizeY}))/2) min({screenSizeX,windowSizeX});min({screenSizeY,windowSizeY}) down
