### ISSUE TITLE
Problem with defaults

### ISSUE THREAD

**Issue by loshlee** [jigish/slate#208]
Does https://github.com/jigish/slate/blob/master/Slate/default.slate need to be changed? When I load it, I have unexpected results. For example, alt-ctrl-1 and alt-ctrl-2 seem to do the same thing, and cmd-esc appears to have different results depending on what application is active when I use it.

**Comment by jigish** [comment]
It should work fine. The config styles haven't changed at all. What exactly happens in each of those cases?

**Comment by loshlee** [comment]
I guess I mistook screens in instructions to mean spaces or desktops. So with only one screen (whether or not there are multiple spaces or desktops, alt-ctrl-1 and alt-ctrl-2 should probably appear to do the same thing. However, If I create a new admin account on my Mtn. Lion 10.8.2+ system and launch Slate from the Applications folder, then launch AppleScript Editor, TextWrangler, and Safari, pressing cmd-esc shows different hints depending on what application is active when the action is triggered.

**Comment by jigish** [comment]
Yah, "screen" means physical screen. Also the default hint behavior is to order the hints left to right. Check out the config "windowHintsOrder" in the readme for more details. Side note: "persist" seems like the best option for "windowHintsOrder" but it may or may not work properly currently. Also, it is memory and computationally intensive. I wouldn't suggest using it.
