### ISSUE TITLE
Modal bindings not working anymore

### ISSUE THREAD

**Issue by ealimonda** [jigish/slate#209]
Version 1.0.17 seems to break my modal keybindings.  Specifically, with the following lines in my ~/.slate:

```
bind `:f1,shift grid padding:5 1280x800:6,3 1280x1024:6,4
bind 1:f2,shift focus 'iTerm'
bind 2:f2,shift focus 'MacVim'
```

the three bindings trigger (without any modal activation) by pressing respectively tilde (shift-backquote), exclamation mark (shift-1) and at (shift-2), rather than requiring the modal sequences, respectively, shift-f1 backquote, shift-f2 1, shift-f2 2 as they are supposed to.

I've bisected the issue and it appears to have been introduced in e2fdb02e1fce172287dc0b1861028775ea4b356a

**Comment by jigish** [comment]
damn, sorry that snuck in there. just pushed a new version with a fix. thanks for doing the bisect!
