### ISSUE TITLE
Excessive Logging in 1.0.18

### ISSUE THREAD

**Issue by mfrister** [jigish/slate#210]
Since the update via Sparkle to 1.0.18 I'm seeing lots of log messages in the system log.

For example window title changes are logged, so each time I open a new page in Chrome, its title is logged.

The version distributed via Sparkle should have debug logging disabled by default.

**Comment by jigish** [comment]
weird. i modified my publish script. maybe something went wrong and it published the debug version instead of the release one. i'll make sure the next version won't have any logging.

**Comment by jigish** [comment]
Fixed and pushed in 1.0.19. there are still a couple random lines I forgot to clean up but those were there before 1.0.18. I'll remove those in 1.0.20

**Comment by mfrister** [comment]
Much better, thanks!
