### ISSUE TITLE
'focus' does not work with Adium chat windows

### ISSUE THREAD

**Issue by eproxus** [jigish/slate#211]
The `focus` command does not jump to or from Adium chat windows using Slate 1.0.15 and Adium 1.5.4.

**Comment by jigish** [comment]
Can you try updating to the latest Slate? I use focus regularly to focus Adium chat windows and it seems to work fine for me. Also are you trying to focus using the app name or directionally? what does your binding look like?

**Comment by eproxus** [comment]
Seems to work with latest. Just a note: I've got a feeling "Automatically Check for Updates" doesn't seem to work?

**Comment by jigish** [comment]
it does work it just isn't really predictable lol. I've gotten the notification myself, but since slate just sits there and runs in the background the sparkle framework doesn't really check automatically very often. it usually checks when slate is opened.

**Comment by eproxus** [comment]
Ah, that explains it. I always put my computer to sleep, so no update there... :smiley:
