### ISSUE TITLE
Support for multiple screens/desktops

### ISSUE THREAD

**Issue by kmanville** [jigish/slate#213]
I would love the ability to "throw" windows to other screens as is currently possible with multiple monitors.

edit: looks like this has been discussed here https://github.com/jigish/slate/issues/78
sorry, I'm new to OS X and didn't realize they were called spaces!

**Comment by jigish** [comment]
no worries :) - closing this as it is a duplicate.

For the record, spaces support is high on my priority list but it is definitely not an easy problem =/.
