### ISSUE TITLE
Pass operation parameters to win.doOperation()

### ISSUE THREAD

**Issue by robcowie** [jigish/slate#215]
It would be great to be able to dynamically generate parameters for an operation and pass them to `win.doOperation()` (or `operation.run()`, which does seem to accept an options array though it isn't used).

For example. Given

``` javascript
var boom = slate.operation('move', {
    'x': 'screenSizeX/2',
    'y': 'screenSizeY/2',
    'width': '100',
    'height': '100'
});
```

This runs the operation with params as defined.

``` javascript
slate.bind('c:ctrl,alt', function(win){
    win.doOperation(boom);
    return;
});
```

The operation might be run with different params thus

``` javascript
slate.bind('c:ctrl,alt', function(win){
    win.doOperation(boom, {'x': '50', 'y': '50'});
    return;
});
```

**Comment by jigish** [comment]
I suppose this could be a nice shorthand, but what would actually be happening in the background (the way it is coded up right now) is Slate would have to create a brand new operation. As such I wanted to make sure the user knows that is happening so the way you would do that is:

```
slate.bind('c:ctrl,alt', function(win){
  win.doOperation(slate.operation('move',
    'x': '50',
    'y': '50',
    'width': '100',
    'height': '100'
  });
  return;
});
```

Now that I think about it, though, I can probably make a function `dup` on the operation object that will duplicate the operation and update the given parameters. I'll try to implement that soon.

**Comment by robcowie** [comment]
Ah, ok. This is indeed how I've approached it for now. `operation.dup(options)` would be a nice convenience.

**Comment by jigish** [comment]
implemented. will push a new version tonight.
