### ISSUE TITLE
What version of javascript is supported?

### ISSUE THREAD

**Issue by robcowie** [jigish/slate#216]
Useful to know what version of javascript is used to run js configs. It would be great if it were 1.8 so we could use generator expressions.

**Comment by jigish** [comment]
Unfortunately I don't think 1.8 is supported.

The underlying code is using a `WebView` to execute the javascript so as a rule of thumb if you can do it in Safari, you can probably do it in your `.slate.js`. This may not be 100% accurate but it should be a good test.

I'll try to whip up a quick test page with some mocks of the `slate` object functions so people can test out their `.slate.js` to make sure it is syntactically correct. As of right now the best way to do this is `slate.log` and trolling the OS X Console :) while running Slate.
