### ISSUE TITLE
NSRangeException

### ISSUE THREAD

**Issue by arlobryer** [jigish/slate#217]
I suspect I'm just misusing the throw directive however, when I add a line like:

```
bind <:cmd;ctrl;alt throw 1 resize
```

With any number 0 or 1 (whilst using two screens), I get an alert saying:

NSRangeException
**\* -[_NSArryl objectAtIndex:]: index 0 beyond bounds for empty array

Could you advise me on what I'm doing wrong?

**Comment by arlobryer** [comment]
Actually this is to do with the '<' that is in the command. I wanted ',' anyway.

**Comment by jigish** [comment]
Reopening this so I can fix the exception and display a more informative error.

**Comment by jigish** [comment]
fixed. the better error will be in the next version.
