### ISSUE TITLE
Way to check if window is resizeable in JavaScript?

### ISSUE THREAD

**Issue by Westacular** [jigish/slate#218]
Would it be possible to add a function to the JS Window object that returns whether or not a window is resizable?

**Comment by jigish** [comment]
Not yet. From the accessibility API there isn't actually a way to check if a window is movable/resizable. You pretty much have to try to move it and see if it works. If it doesn't work it'll throw an exception which I catch internally and then most of the time I'll return `false` on the `operation.run()` or `window.doOperation()` method.

I'll try to add a function that tries to "move" the window to the same location that it is to see if it can be moved as well as a function that tries to "resize" the window to the same size it is to see if it can be resized. Sort of awkward, but it should work.

**Comment by Westacular** [comment]
It's not a high priority thing for me. In the situation where I'm envisioning using it, I could just as easily check the return value for `window.doOperation()` and add a fall-back that moves the window without resizing it.

**Comment by jigish** [comment]
fair enough. it is done either way :). isMovable and isResizable are methods on the window object. I'll push a new version some time today with the change.
