### ISSUE TITLE
javascript action not run when active app has no window

### ISSUE THREAD

**Issue by thomasjachmann** [jigish/slate#222]
When you bind an action to a keystroke and hit that key, the action only gets run when the active application has a window.

Example: Safari is the active app and has a browser window open, then hitting the key will run the action. When Safari has no windows open, hitting the key will not run the action.

**Comment by jigish** [comment]
fixed. the window argument will be undefined if there isn't a focused window. i'll push a new version today with this change.

**Comment by thomasjachmann** [comment]
You're awesome!
