### ISSUE TITLE
[Question] is slate able to automatically position windows?

### ISSUE THREAD

**Issue by tr3buchet** [jigish/slate#223]
I'm attempting to find an application I can use to cause osx to open windows in the same position every time. As an example, since mail.app opens email in random positions on the screen, I would like to "pin" the mail window to the right side of the app itself, so that every time I open an email the window which is created to show the email is located at example the same place with the same size. This should happen regardless of how many of these emails I open.

Reading the documentation and what not I am seeing that I can bind keys to cause the windows become arranged in certain ways. I wasn't clear whether a layout can be applied causing new windows to line up as well.

**Comment by jigish** [comment]
It actually isn't as of now. I've looked in to this briefly and it is really difficult to accurately do this. A lot of times when you get a notification of a new window opening the window isn't ready to be moved yet and there isn't really an event that says "hey i'm ready to be moved now".

The closest thing slate has is defaults which will activate a layout when a given screen configuration (monitor setup) is seen.

Sorry =/
