### ISSUE TITLE
Can't use "," or ";" as part of a modifier or modal-key

### ISSUE THREAD

**Issue by chdiza** [jigish/slate#225]
I would love to use the comma in modifier lists and modal-key lists, but I can't seem to do so.  Same for the semicolon.

**Comment by chdiza** [comment]
Let me revise the request to be only about using those keys as part of a modal-key string.  I now see in the README that the modifier list is very short.

**Comment by jigish** [comment]
hmm. I'll have to find a good way to allow this. will do it soon.

**Comment by chdiza** [comment]
The reason I ask is that there are so many nice things to do with slate but I'm running out of memorable hotkey combos that don't conflict with either OSX or those built into various apps.

Being able to mimic Vim's `<leader>` and `<localleader>` with `;` and `,` would help.

And what would REALLY help is if the slate analog of what Vim calls the `<lhs>` of a mapping could be more than one character.  For instance, if we could do `bind res:cmd,alt relaunch`, or 
`bind pu:cmd,alt push up`
`bind pd:cmd,alt push down`
it would be mega-handy.  Combining all this to get for example `bind pu:comma` would be the greatest thing since sliced bread.

**Comment by mgax** [comment]
I agree this would be extremely useful, as it would reduce cognitive load for memorizing key combos. This use case was my original motivation for integrating a scripting language. Perhaps an api for on-the-fly binding and unbinding of hotkeys would be sufficient.
