### ISSUE TITLE
The sign that the modal key is active (the blue icon) is hard to see...

### ISSUE THREAD

**Issue by chdiza** [jigish/slate#226]
When a modal key has been pressed and slate is waiting for input, it makes the menubar icon blue as a sign of this.

However, it is _really_ hard to see that sign toggle on and off, from one's peripheral vision (even on a small monitor).

Perhaps if the _background_ of the menubar icon turned blue it would be easier to see out of the corner of my eye that the modal key is still active.  Actually, it would be better if the background turned black or red (or even yellow), since the blue is too close to the black.

Even better still (but more work) would be an optional even bigger sign, like a bezel or something like that.

**Comment by jigish** [comment]
Interesting. I can add a config like `modalKeyActiveIndicator` or something that can allow you to choose which style you want. Just to make sure, here is a list of styles you are suggesting:
- Original icon color change to blue (default)
- Icon background change to blue
- Bezel (you mean a full screen bezel?)

Also, I'll probably end up adding a config like `modalKeyActiveIndicatorColor` which will let you set the color to whatever you want.

**Comment by chdiza** [comment]
> - Original icon color change to blue (default)
> - Icon background change to blue
> - Bezel (you mean a full screen bezel?)

I tried hacking the first two options by tweaking the file "statusActive.pdf".  Turns out that this hardly helps at all, even with a red background (or even with just a plain, red square!).  It's still too hard to see out of peripheral vision, even on a small monitor.

The third option, by which I meant something like the bezel that appears when one hits the volumes buttons on the keyboard, seems like the best way to go.  This bezel needn't appear where the OS ones do.  Maybe it could be in the upper-left corner or something.

Come to think of it, it the indicator could be that the entire Mac menubar changes color, or is blacked out, or something like that, then _that_ would be visible out of peripheral vision.  (Like the downloadable "Menu" interface for Quicksilver in appearance).

**Comment by kevinastone** [comment]
+1 on this.  I'd prefer a bezel that shows the modal-key is activated similar to how Moom does it centered on the screen:

![screen shot 2013-05-30 at 9 42 00 am](https://f.cloud.github.com/assets/1234915/586207/f12bc302-c947-11e2-99ce-0fcc13567e7d.png)
