### ISSUE TITLE
Screens should be ordered by default from left to right 

### ISSUE THREAD

**Issue by philc** [jigish/slate#23]
This is the least surprising behavior and implicitly addresses issue #7, where connecting your screens in a different order will re-order your screen numberings. I think it's less work than defining screens based on resolution.

In particular, defining screens based on resolution doesn't help when you have multiple monitors of the same resolution (e.g. two 24" side-by-side).

I haven't tested the latest on master so apologies if it's there already, but I didn't see it in the commit stream.

**Comment by jigish** [comment]
Good call. Unfortunately the screen IDs apple uses are ordered in the following order:

0 = always main screen (the screen with the menu bar)
after that, they are ordered in the order in which they were plugged in.

I'll try to add a config option that will make the screen IDs go from left to right, and map them internally to the screen IDs that apple uses.

**Comment by jigish** [comment]
Ah -- just thought of something interesting. Screens are also allowed to be above/below. I'll make it so it starts at 0 at the top-left screen and fills in this order:

```
0  1  2  3
4  5  6  7
```

**Comment by philc** [comment]
Yes, that would be great. In case the API doesn't give you that information, you could of course determine a screen's position from the bounding rect of each nsscreen in relation to the others.

**Comment by philc** [comment]
This kicks my butt every day -- sending a window to screen #N is not reliable as those numbers are always changing around.

**Comment by jigish** [comment]
Finally got to this in 0.4.9. Sorry, real life gets to me when the dancing season starts.

Here is how it works:

Default (no work on your part): screens are ordered from left to right (by the top-left origin X coordinate, falling back on Y coordinate if they are the same). This means they are _not_ ordered as I listed in my above comment.

If you want to use the old style ordering, you can set the config "orderScreensLeftToRight" to false. By setting this to false, the default handling of screen IDs remains how it was in 0.4.8, but you can also use the "ordered:" prefix to the screen ID to make it work for that particular binding as if "orderScreensLeftToRight" was true.

**Comment by philc** [comment]
Just tried it and it works great. Thanks again!
