### ISSUE TITLE
Problem with .slate.js

### ISSUE THREAD

**Issue by kunegun** [jigish/slate#230]
Hi, I'm new here.

I was using slate for a month, but when i updated to the new version (above 1.9), the program never work again!

I don't know why? I think is for the slate.js, where I have to put it?

Thanks!

**Comment by robcowie** [comment]
`.slate.js` must be in your home directory, the same folder as your existing `.slate`

**Comment by kunegun** [comment]
It doesn't work for me!

This ("[SLATE] -------------- Finished Loading Config --------------") never appears at the console, and i don´t know why.

**Comment by robcowie** [comment]
Post the contents of your .slate.js file, and it's file path to https://gist.github.com or similar and I'll have a think.

**Comment by kunegun** [comment]
I have the .slate.js that is in the example of slate, i didn´t change anything

https://github.com/jigish/dotfiles/blob/master/slate.js

**Comment by robcowie** [comment]
That example works for me if I put it at `~/.slate.js`. Where exactly is your file? Have you restarted slate?

**Comment by kunegun** [comment]
I put this archive at Contents/Resources/ but i can´t give the name of .slate.js it says that . is reserved to system.

**Comment by jigish** [comment]
I'm sorry, can you be a bit more clear about what is going on? Here is the information we need:
1. Are you trying to use a `.slate` or a `.slate.js` or both?
2. where are you putting your `.slate` and/or `.slate.js`? They should go in your home directory (`~/`)
3. If you don't mind, can you run `ls -al ~/.slate*` in your terminal and paste the output here? It should look something like this:

```
-rw-r--r--  1 jigish  staff    31 Jan 26 14:43 /Users/jigish/.slate.js
```

or

```
-rw-r--r--  1 jigish  staff    31 Jan 26 14:43 /Users/jigish/.slate
```

or

```
-rw-r--r--  1 jigish  staff    31 Jan 26 14:43 /Users/jigish/.slate
-rw-r--r--  1 jigish  staff    31 Jan 26 14:43 /Users/jigish/.slate.js
```

**Comment by kunegun** [comment]
I'll found the problem, it was the . before the name of the archives

Which is the best option to do this? i did it with the terminal, but now this archives are invisible

thanks!

**Comment by robcowie** [comment]
By default the Finder does not render files whose name begins with a dot. If you want to work with these files, the terminal is the best option.

So to confirm, the .slate.js config file (it's a file, not an 'archive' :smile: ) is in the folder `/Users/<yourname>/`?

**Comment by kunegun** [comment]
Yes! it's running ok now!

the .slate.js config FILE (:P) is in the folder /Users/<yourname>/

thank you so much!
