### ISSUE TITLE
Config must come before bind

### ISSUE THREAD

**Issue by veered** [jigish/slate#234]
In my .slate file, I had all of my configs below all of my binds and was frustrated to see that windowHintsSpread = true was not spreading the hint icons apart. However, when I moved all of my configs above my binds the hint icons spread apart.

Here is the broken .slate:
https://gist.github.com/Veered/4759131

This is the working .slate file:
https://gist.github.com/Veered/4759121

**Comment by jigish** [comment]
yah, I need to be more clear about this in the docs I guess. The file is read top-down so anything that isn't declared before a bind may not be used for that bind. I'll update the readme.

**Comment by jigish** [comment]
updated the readme
