### ISSUE TITLE
Stopped working in Mountain Lion OSX 10.8.2

### ISSUE THREAD

**Issue by 74io** [jigish/slate#235]
Hello there,

I love slate, but after a recent update (can't remember which sorry) it just stopped working.

I am only posting the question here out of desperation. I would appreciate any help or pointers that might get this wonderful app working again.

I am using Mac OSX 10.8.2.

Kind regards

Ryan

**Comment by 74io** [comment]
OK forgive me. It was the same .slate.js file issue. I had to find a .slate.js file (not obvious and I used the one posted here: https://github.com/jigish/slate/issues/230

It would be handy under the 'Configuring Slate' option to say that you need a .slate.js file and here is how to get it. It appears there is no fall back like the .slate file.

Many thanks for all you hard work. I now have the app back up and running.

**Comment by jigish** [comment]
you actually need a `.slate.js` _or_ a `.slate`. You shouldn't need both. Also, if you don't specify either slate should use the default config. If this is not the case please let me know. I need to fix that.

**Comment by snarfed** [comment]
confirmed, i'm using slate 1.0.24 on os x 10.8.2, and it doesn't work unless you have a .slate or .slate.js file.
