### ISSUE TITLE
Window/App change event listeners

### ISSUE THREAD

**Issue by mlegenhausen** [jigish/slate#239]
It would be nice if I could listen, when a new app or window was opened. Something like:

```
slate.on('app', function(event) {
});

slate.on('window', function(event) {
});
```

This would allow me to arrange the windows of an app automatically on start up without pressing any keys. Or is this already possible?

**Comment by jigish** [comment]
This is an interesting idea. May be awkwardly complicated to implement though. Have you checked out layouts and defaults? They may tide you over until I figure out a way to implement this well.

**Comment by jigish** [comment]
ok I've implemented a couple things. I'll update the wiki when I get a chance and link the page here. should be in the next release.

**Comment by jigish** [comment]
[check this out](https://github.com/jigish/slate/wiki/Events)
