### ISSUE TITLE
push commands not undoable

### ISSUE THREAD

**Issue by sabberworm** [jigish/slate#246]
The undo command does nothing when used after a `push right` command.

However, when I emulate `push right` using `move screenOriginX+screenSizeX-windowSizeX;windowTopLeftY windowSizeX;windowSizeY`, I can use `undo` to revert the change.

Same goes for all other `push` commands I’ve tried (`push up`, `push down`, `push left`, `push right`; However, I’ve not tried using any of the optional params (`style` and `screen` or the `direction` values `top` and `bottom`).

**Comment by jigish** [comment]
merged. this will be fixed in the next version
