### ISSUE TITLE
Binding parse error when starting up Slate when referencing unconnected screens

### ISSUE THREAD

**Issue by philc** [jigish/slate#25]
I suspect if you reference a screen number which is not currently connected, Slate has trouble parsing bindings related to that screen. The third command in this series:

bind 1:ctrl;cmd throw 0 resize
bind 2:ctrl;cmd throw 1 resize
bind 3:ctrl;cmd throw 2 resize

Causes Slate to give this error in a message box upon startup (titled "Unable to Parse Binding"):

Unable to parse '**\* -[NSCFArray objectAtIndex:]: index (2) beyond bounds (2)' in 'bind 3:ctrl;cmd throw 2 resize'

**Comment by jigish** [comment]
Finally Fixed in 0.4.10

**Comment by philc** [comment]
Excellent.
