### ISSUE TITLE
a way to automatically change to a layout when an application is opening or quitting

### ISSUE THREAD

**Issue by pvinis** [jigish/slate#261]
I have a layout "normal" and a layout "programming".
It would be nice to have an automatic way, so that when i open macvim, the layout switches, and when i quit it, the layout switch back.

**Comment by Westacular** [comment]
Thanks to the recent addition of [event listeners](https://github.com/jigish/slate/wiki/Events), you can already do this using javascript.

**Comment by pvinis** [comment]
and where do i put them? in the `.slate` file?

**Comment by Westacular** [comment]
In `.slate.js`

[See here](https://github.com/jigish/slate/wiki/JavaScript-Configs) for getting started with JavaScript configs.

You'll probably want something like

``` javascript
var programmingLayout = slate.operation("layout", { "name" : "programming" });
var normalLayout = slate.operation("layout", { "name" : "normal" });

slate.on("appOpened", function(event, app) {
    if (app.name() === "MacVim") {
        programmingLayout.run();
    }
});

slate.on("appClosed", function(event, app) {
    if (app.name() === "MacVim") {
        normalLayout.run();
    }
});
```

**Comment by pvinis** [comment]
awesome! thanks.

**Comment by rpunkfu** [comment]
OMG, this is amazing!
