### ISSUE TITLE
.slate.js doesn't get loaded anymore

### ISSUE THREAD

**Issue by deiga** [jigish/slate#275]
I'm not really sure whats happening here. I just noticed that my bound keys don't work anymore, which led me to notice that `S.log` doesn't print anything into console.

I had to move my bindings to `.slate`, but I can't move everything.

Any help? :)

https://github.com/deiga/dotfiles/blob/master/slate
https://github.com/deiga/dotfiles/blob/master/slate.js

**Comment by puffnfresh** [comment]
Same problem here.

**Comment by puffnfresh** [comment]
Turns out I had a syntax error. Ran JSHint over my .slate.js config. Works fine now!

**Comment by deiga** [comment]
Figured out why my slate doesn't load.

```
var hyper = "ctrl;shift;alt;cmd";
...
S.bnda({

    // Layout Bindings
    "padEnter:ctrl" : universalLayout,
    "space:ctrl" : universalLayout,

    // App Bindings
    "t:"+hyper : S.op("focus" , { "app" : "iTerm" }),

    // Grid
    "esc:alt" : S.op("grid")
});
```

The `"t:"+hyper` row causes the problem, if I comment it out then everything works

**Comment by puffnfresh** [comment]
@deiga that's not syntactically valid JavaScript. Would have to write:

``` javascript
var bindings = { ... };
bindings["t:" + hyper] = S.op("focus" , { "app" : "iTerm" });
S.binda(bindings);
```

**Comment by deiga** [comment]
This is weird, since it did work earlier... and the documentation has an example just like mine `"right:cmd" : S.op("focus", { "direction" : "right" }),`
