### ISSUE TITLE
Screen ordering doesn't take into account monitor layout updates

### ISSUE THREAD

**Issue by philc** [jigish/slate#28]
I have two Apple thunderbolt displays daisy chained together. The screens are laid out like this:

```
Left    Right
   Laptop
```

OSX unfortunately does not remember the Apple displays layout across disconnects. 50% of the time I plug in to these monitors, I need to swap their layout positions by using the Display Preferences Pane.

After doing this adjustment via Preferences, the Slate screen numbering does not update -- screen 1 could now be on the right, while screen 3 is on the left, for instance.

Do you think this problem is solvable? Mechanically this could be handled by polling for position changes every few seconds, but should Slate dynamically change its screen numbering in response to layout changes?

**Comment by jigish** [comment]
This is totally possible. I can just update screen positions every time a binding is triggered as it is pretty inexpensive. I'll try to fix it soon.

**Comment by jigish** [comment]
Ok so you'll have to show me the issue. I cant get it to repro.

**Comment by philc** [comment]
You're right, I was out of date. I'm a noob.
