### ISSUE TITLE
Dynamically retrieve list of screens and resolutions

### ISSUE THREAD

**Issue by ProLoser** [jigish/slate#291]
I'm trying to create a simple config that will keep taking snapshots as I modify my environment, and will automatically recover the snapshot any time I change windows. This is what I have thus far:

``` js
var save = function(){
  slate.operation("snapshot", {
    "name" : 'background',
    "save" : true
  });
};

var load = function(){
  slate.operation("activate-snapshot", {
    "name" : 'background'
  });
};

// slate.on('windowClosed', save);
// slate.on('windowMoved', save);
// slate.on('windowResized', save);
// slate.on('windowTitleChanged', save);
// slate.on('appOpened', load);
// slate.on('screenConfigurationChanged', load);
```

I believe the best solution would be to change the `name` of the snapshot to be my screen resolutions, but I don't know how to arbitrarily retrieve them (all your examples show screen resolutions hardcoded).

Is there a way to get screen resolutions dynamically so I can use them as part of the snapshot name?

**Comment by bittner** [comment]
Just a question (as I've just discovered Slate):

Can't Slate simply store all active windows into the configuration file, and restore them as soon as the external monitor(s) is/are reconnected? -- Is this what your code is trying to do?

**Comment by ProLoser** [comment]
@bittner yes, I'm trying to make 1 config for everyone actually, not just a fully custom one: https://gist.github.com/ProLoser/a55406df872c83dd71ea (it has reslate at the top half though).

All keyboard shortcuts needed are <kbd>ctrl</kbd>+<kbd>option</kbd>+<kbd>cmd</kbd>+<kbd>up/down/left/right/space</kbd> and it handles both resizing, relocating to different monitors, moving around, and lets you on-the-fly change grid systems from halves to thirds (and hopefully more if I can fix the arithmatic). It's not perfect though, but worth playing with and improving hopefully.

I also wanted it to sort of reorganize your screen whenever you change monitor configurations. Note that I'm retrieving the current monitor configuration and using it as the config name.

However, I'd like to also store arrangements of windows and applications that aren't open, and when they DO open, place them back to their normal position for that monitor configuration. Although lately, I've slightly been finding OSX has been smarter about doing such things natively.

**Comment by bittner** [comment]
> I also wanted it to sort of reorganize your screen whenever you change monitor configurations.

That's what I'm mainly after. Especially, when I attach or detach a(nother) monitor. [Stay](http://cordlessdog.com/stay/) (by Cordless Dog) does this for me for now, but it's good to see there's an Open Source solution too.

Slate doesn't do the trick out of the box. It's not storing and restoring windows automatically. I'm wondering if I really have the right concept of what Slate should do.

**Comment by ProLoser** [comment]
@bittner slate does whatever you configure it to do. I am fully aware of stay, but I don't think I was willing to pay or I think it had buggy behavior. I was saying that I'm writing a config file that does what Stay does.

**Comment by ProLoser** [comment]
I think the other reason I started implementing my own variation to stay is because it doesn't work with chrome well or other apps that have the titles of the window change a lot and I didn't feel like doing the whole "link application" thing over and over.
