### ISSUE TITLE
Automatically create new snapshot when a new screen is plugged in

### ISSUE THREAD

**Issue by lopopolo** [jigish/slate#30]
The worst is when I plug my laptop into a projector and all of my windows get resized because all of my displays are resized to 800x600.

Is it possible to save my window configuration automatically when a new monitor is plugged in but before all the resizing happens?

**Comment by jigish** [comment]
hey man. i'll definitely try to add this. the problem is there isn't any "screen configuration is about to be changed" notification. only a "screen configuration has already changed" notification. I may be able to do some interesting things and get this done. i'll keep you posted.

**Comment by jigish** [comment]
unfortunately this is not really possible unless i constantly keep a snapshot of the current window configuration. There is no "the screen configuration is about to change" notification. I'm closing this issue, but I'll point you to Issue #42 which adds a menu option to take a quick snapshot. I know it doesn't fix this use case but it is better than nothing. I'll keep this in mind though and if I figure out a clean way to do this, I will.

**Comment by lopopolo** [comment]
Thanks for investigating, Jigish. #42 looks like it will do the trick
