### ISSUE TITLE
Configuration Helper

### ISSUE THREAD

**Issue by jigish** [jigish/slate#31]
Create configuration helper menu item

**Comment by jigish** [comment]
getting the UI down for this is a _lot_ more complicated than it is worth. the chances that users would actually use this are slim to none. getting rid of the milestone for this. maybe i'll implement it in the future. for now, it is not going to get in the initial release.

**Comment by philc** [comment]
Agreed, this will be a lot of effort.

**Comment by asawilliams** [comment]
how about just a shortcut to open the config file in a text editor?  I find it helpful when trying to remember which commands do what and for fixing command collisions I occasionally find.
