### ISSUE TITLE
CMD+Tab Replacement

### ISSUE THREAD

**Issue by jigish** [jigish/slate#32]
Create CMD+Tab replacement

**Comment by jigish** [comment]
1. Cycle through apps both ways
2. Quit app
3. Force quit app
4. Change size
5. Names or Icons or both
6. Horizontal or Vertical

**Comment by philc** [comment]
If you haven't already vetted lightswitch X for inspiration, you should. The most important feature for me has been CMD+TAB raises only the frontmost window of the app, not the entire thing.

Also, its feedback of CMD+Q while CMD+TAB is held down is much better than OSX's.

**Comment by jigish** [comment]
Actually LightSwitch X is exactly where I got my inspiration from. I've been using it for a while (even through the stupid "pay for this" popups). I'll definitely steal a lot of the nifty features from it.

**Comment by jigish** [comment]
1, 2, 3 done + hiding/showing done. Right now it raises the entire app, need to change the way I focus things (and add this as a customizable option).

To do:
1. Names/Icons/Both
2. Horizontal or Vertical
3. Apps only or all windows
4. fix focus
5. hold to keep cycling (stop at edges)
6. mouse scroll up/down to cycle?

**Comment by jigish** [comment]
also -- severe limitation in mac os x that disallows hijacking CMD+tab. I'm currently looking into how to get around that because Witch clearly does it so it can be done.

**Comment by jigish** [comment]
2 and 5 are done now. also want to add the ability to trigger the operation when hitting the "back" binding (like how cmd+tab AND cmd+shift+tab trigger the default app switcher). So to do:
1. Names/Icons/Both
2. Apps only or all windows (ordered by apps? various UI/key options?)
3. Trigger operation from back binding
4. fix focus (is this possible?)
5. mouse scroll up/down to cycle? (probably not for initial version)

**Comment by jigish** [comment]
1 and 4 done. Left:
1. Apps only or all windows (ordered by last focus)
2. Trigger operation from back binding

**Comment by jigish** [comment]
For 1.0, the additional features will not be available. they will be in 1.1 and tracked by Issue #54 and #55.
