### ISSUE TITLE
Anyone having problems with Apple Thunderbolt display?

### ISSUE THREAD

**Issue by digitalronin** [jigish/slate#326]
I don't know if this is a problem with Slate or not.

I've been using Slate on my MacBook air for a while, and it works perfectly, including when I had second monitors connected (a Dell and a Ben Q).

I recently got an Apple thunderbolt monitor, and I'm having a strange problem with it. If I plug it in with the laptop switched on, then I can't start system preferences, I can't shut down the laptop, and I can't use the Apple monitor for sound.

If I boot the laptop into a test user account, then I can connect the monitor and everything works. If I connect the monitor with the laptop powered off and then boot up into my account, everything is fine.

So, the problem must have something to do with the software I use in my main account. I don't know if this has anything to do with Slate, but it's the only monitor related add on I use, so it seems like a good bet (although quitting slate before connecting the monitor made no difference).

Has anyone else experienced problems like this? Can anyone give me any hints as to how I might track down the root cause?

**Comment by RayneIO** [comment]
It's probably not Slate.  You might check your Console.app for System Log messages.

**Comment by digitalronin** [comment]
For anyone who finds this thread by searching for the problem, it looks like this is something to do with USB 2 and USB 3 devices conflicting. With no USB devices plugged into the monitor or the laptop, things work correctly.
