### ISSUE TITLE
App Storeify

### ISSUE THREAD

**Issue by jigish** [jigish/slate#33]
Try to put slate on the app store

**Comment by jigish** [comment]
or use sparkle if rejected

**Comment by philc** [comment]
+1 (so I can follow this issue)

**Comment by jigish** [comment]
submitted to app store for the first time. we'll see what happens.

**Comment by jigish** [comment]
lots of bug fixes. I'm going to pull the current version and re-submit after I fix the bugs.

**Comment by jigish** [comment]
submitted again. shouldn't have to pull it this time.

**Comment by jigish** [comment]
rejected due to:
1. snapshots save files to ~/ which is not allowed.
2. if no ~/.slate, Slate errors out. I'll change it to a warning and add a default config.

**Comment by jigish** [comment]
resubmitted. we'll see what happens.

**Comment by jigish** [comment]
still having issues. they for some reason can't get slate to run without the "can't find .slate" message showing. I even attached a slate file to use =/. Hopefully they can get it figured out soon or I'll have to add some default mappings to fall back on which I really don't want to do.

**Comment by jigish** [comment]
This is a complete fail. I basically can't publish to the app store without having some defaults because they are saying that people expect apps to "just work". Or I'd have to add a configuration manager which will be even worse because under app store guidelines apps can't write to the home directory. So then I'd have to change the location for the .slate file which I'm definitely not going to do. I'm going to try to add defaults and see if they accept that. If not, sparkle it is.

The App Store sucks.

**Comment by philc** [comment]
;-)

**Comment by cespare** [comment]
Slate is a highly configurable app strictly for power uses; i.e. the antithesis of "good" Mac OS software.

**Comment by jigish** [comment]
Ok. I've added default configs. They will _only_ exist if you do not have a .slate file in your home directory. Hopefully this appeases the App Store testers. Submitting again...

**Comment by dcai** [comment]
Good luck with the App Store submission, how is that going?

(Just discovered this app, it's awesome!)

**Comment by jigish** [comment]
lol it is not going. Apple keeps rejecting because I'm using pretty low level stuff. I'm going to use Sparkle instead. Look for an update soon with updates through Sparkle.

**Comment by dcai** [comment]
@jigish Looking forward to it, thanks for the great work :)

**Comment by jigish** [comment]
Sparkle now in 1.0.0!

there is a bug in Sparkle right now that doesn't delete the old version of the app. I filed a bug on Sparkle asking about it. Hopefully it'll get fixed soon.
