### ISSUE TITLE
Put apps in fullscreen mode with Slate.

### ISSUE THREAD

**Issue by jumoel** [jigish/slate#336]
I have two scenarios: my laptop alone, and my laptop connected to a large external monitor.

On the external monitor, the apps are currently being tiled with slate. I'd like to be able to make Slate put the apps in fullscreen mode when I'm not connected to the monitor.

Is this possible?

**Comment by slumos** [comment]
I just installed Slate hoping it would be able to do this.  Every time I plug in my large display I have to switch around to all my apps taking them out of fullscreen mode, and then put them all back into it when I unplug.

**Comment by kevinastone** [comment]
:+1:

**Comment by am** [comment]
I think we all agree on that, it's time to move-on and make a PR :sweat_smile:

**Comment by sdegutis** [comment]
This commit may help: sdegutis/hydra@64353f2d83116dc8a7788f432dec185f9c39a594
