### ISSUE TITLE
"windowHintsOrder persist" causes "hint" to function only once

### ISSUE THREAD

**Issue by wwalker** [jigish/slate#342]
My config is essentially the default config, plus some "corner" actions, plus:

config windowHintsIgnoreHiddenWindows false
config windowHintsShowIcons true
config windowHintsSpread true
config windowHintsOrder persist

It works fine as long as I don't "config windowHintsOrder persist".  Once I set persist, cmd-esc (bound to "hint") works once, then "hint" (cmd-esc) does nothing.

If I "Relaunch and Load Config" keys work again, until I use cmd-esc (hint) again.  At that point, cmd-esc is dead again.

I'm running 1.0.25, on 10.8.4 on a 15" MBP w/retina . I have 4 iterm2 windows, adium, preview, chrome, and cord open.

**Comment by chuckg** [comment]
+1 verify this bug. Turning no `persist` for `windowHintsOrder` causes hints to only work once. Reloading/restarting Slate enables another single use. Disabling the `persist` option returns the behavior to normal.

@wwalker This has been a source of frustration for me from day one, thank you for pinpointing the exact problem so I can workaround my config and get back on track using the awesome slate hints.

**Comment by wwalker** [comment]
Dead project.
