### ISSUE TITLE
The OmniGraffle app is not targetable in a Slate layout

### ISSUE THREAD

**Issue by philc** [jigish/slate#347]
I can use Slate shortcuts to move OmniGraffle around, but I can't target it by name in a layout.

Here's a snippet from my .slate. Every other app in this layout works. Unless I'm missing an obvious typo, OmniGraffle should work as well. I've tried various casings of the app name "OmniGraffle".

```
layout 3monitors 'OmniGraffle':SORT_TITLE,REPEAT               ${1-left}
layout 3monitors 'iTerm':SORT_TITLE                         ${1-left}
layout 3monitors 'Google Chrome':SORT_TITLE,REPEAT               ${1-right}
layout 3monitors 'Chromium':SORT_TITLE,REPEAT             ${1-right}
layout 3monitors 'Emacs':SORT_TITLE,REPEAT             ${2-left} ${2-right}
layout 3monitors 'MacVim':SORT_TITLE,REPEAT             ${2-left}
```

You should be able to quickly reproduce this by downloading omnigraffle [here](http://www.omnigroup.com/download/latest/omnigraffle).

This is with slate 1.0.25.

**Comment by rafd** [comment]
It works for me, but I had to list the app name as 'OmniGraffle Professional'

You can check the names of the apps that Slate detects by clicking on Slate in your toolbar, then selecting 'Current Window Info'

**Comment by philc** [comment]
Awesome. In my case, it was Omnigraffle 6. Thanks for the tip!
