### ISSUE TITLE
Trouble on Mavericks

### ISSUE THREAD

**Issue by chdiza** [jigish/slate#353]
When launched on Mavericks, I keep getting the dialog that says something like "Slate needs to enable Assistive Devices".  I click OK, but then nothing happens, and the next time I launch Slate I get the same thing.

I went to the Accessibility preference pane, and there seems to be no such button or switch to turn Assistive devices on.  I seem to recall there used to be such a button.  Perhaps this aspect of the system has changed in Mavericks, and perhaps Slate needs to adapt to it.

**Comment by loshlee** [comment]
http://t.co/8ZQHCKSKKh
Be sure to search the comments for "drag".

**Comment by chdiza** [comment]
Thanks, but I had the same problem as whoever posted a few posts down under that, where the app is already listed (and checked) in that window, but the dialog keeps happening over and over anyway.

The poster hoped it would be fixed by the time 10.9 was released.  Alas, it is not.  Apparenly not Slate's fault, either.  But maybe Slate can tweak itself to step around this.

**Comment by loshlee** [comment]
I seem to have made it work by repeatedly launching and repeatedly placing a check mark in the box in the Privacy tab of Security & Privacy prefpane. Hopefully these settings won't be as volatile as the quarantine settings for downloaded apps.

**Comment by loshlee** [comment]
Nobody else got it working? I'm not using the java configuration, just a .slate file (which isn't extremely packed with options), but what I have seems to be working.

**Comment by jkusachi** [comment]
ive been able to get it working successfully by:
1. upgrading slate (why not?)
2. go to system pref -> settings and privacy -> privacy
3. unlocking via padlock (bottom left), then just clicking the checkbox next to slate

i only had to do this once. haven't tried restarting yet to see if it sticks, but im assuming it will.

**Comment by bradwright** [comment]
I made this work by doing what @jkusachi said. Thanks! :+1:

**Comment by chdiza** [comment]
It seems to be working now, after a fresh re-install that I had to do for other reasons.

Will monitor in case it fails to stick after restarts, logouts, etc.

**Comment by Chandler** [comment]
+1 jkasuchi's answer fixed my problem

**Comment by plivesey** [comment]
I have no idea why, but for me, it the accessibility capabilities were already enabled but it still didn't work. I had to:

1. go to system pref -> settings and privacy -> privacy
2. Click on accessibility
3. Click on the padlock to unlock
4. Click on slate and then the - button to remove slate from this list
5. Click on the + button and re-add slate

Then it worked. ¯\_(ツ)_/¯
