### ISSUE TITLE
Any way to control mouse pointer.

### ISSUE THREAD

**Issue by alswl** [jigish/slate#370]
Now I can use `focus` `throw` to control window / desktop, but I still cannot use any function to control mouse.
Is there any way to control mouse pointer?

**Comment by harizvi** [comment]
Not through slate, but you can shell out and use cliclick which is a useful utility to simulate mouse movement and presses. 

See http://www.bluem.net/en/mac/cliclick/

**Comment by alswl** [comment]
Thanks, I try to use chain to call cliclick command after some key press.

**Comment by alswl** [comment]
https://github.com/alswl/.oOo./commit/ee782efa0de30eedf6aada29d1364ca76fab808b
I use sequence to control my mouse. Thanks.
