### ISSUE TITLE
Shell command is invoked, Slate always crashes

### ISSUE THREAD

**Issue by tinmarks** [jigish/slate#388]
All shell commands keep on crashing when invoked via shortcut -- even as simple as `bind t:alt;ctrl shell path:~/ 'echo'`
Same happens when no path is provided.

I get popup saying `NSInvalidArgumentException, launch path not accessible`

**Comment by niels-bom-md** [comment]
@tinmarks why did you close this issue?

**Comment by tinmarks** [comment]
I didn't know before I closed it that absolute path to the program is required.

**Comment by niels-bom-md** [comment]
That's helpful for others to know if they find this issue. Thanks for replying.

**Comment by bbarbosa85** [comment]
I'm having this same issue.
I didn't quite get the solution. Can you send an example on how you solved it?

I can make the commands work without the `path:` argument, but including it doesn't make any difference or fails with the message above.
