### ISSUE TITLE
Hints do not appear instantly

### ISSUE THREAD

**Issue by philc** [jigish/slate#39]
If you have many windows, the hints windows appear onscreen separated by 50ms or so --it doesn't feel instant (my original implementation had this problem, and Caleb noticed it as well).

I'm not sure what is taking the time (probably the accessibility API), but if it's window creation time, you could keep those hint windows around in memory and use them again the next time the hint operation is triggered.

**Comment by jigish** [comment]
Yah I noticed this as well. I spent 5 minutes trying to figure out where the time sink was but couldn't find it. I'll try keeping the windows around and see if that helps with the performance.

**Comment by jigish** [comment]
Big fat ugly fail. I tried to keep the windows around and show/hide without releasing the actual object and it doesn't reduce the time at all. I'm going to try a couple more things but I'm 95% sure now that the time sink is the accessibility API.

**Comment by jigish** [comment]
ok I've trimmed as much as I can for now. going to close this, but will keep it in my back of my mind in case I think of something genius.

**Comment by jigish** [comment]
performance improvements will be available in 0.4.16

**Comment by philc** [comment]
I'll give it a try soon. If you decide it's still not fast enough after your improvements, it may help to spin up a bunch of threads and issue each accessibility call in a separate thread, so they're not serial.
