### ISSUE TITLE
how to resize window to quarter screen width and height

### ISSUE THREAD

**Issue by abbood** [jigish/slate#397]
I'm using [slate](https://github.com/jigish/slate) as a window manager, and I would like to bind a certain key combo to automatically resize and position the window as follows
- window width and height will each be half the size of the screen
- the window will be positioned on exactly the top left corner of the screen

I tried this:

```
bind a:shift;cmd;alt push left bar-resize:screenSizeX/2;screenSizeY/2
```

but it's not recognizing that expression.. any ideas?

**Comment by loshlee** [comment]
If I understand correctly, this is what I would add to a slate configuration file to achieve that. It appears to do what you want even if it comprises the entire content of the slate configuration file.

alias lefthalf move screenOriginX;screenOriginY screenSizeX/2;screenSizeY
bind a:shift;alt;cmd ${lefthalf}

**Comment by jgpawletko** [comment]
Here's a excerpt from my .slate file:
_aliases:_

```
alias topleft     corner top-left     resize:screenSizeX/2;screenSizeY/2
alias topright    corner top-right    resize:screenSizeX/2;screenSizeY/2
alias bottomleft  corner bottom-left  resize:screenSizeX/2;screenSizeY/2
alias bottomright corner bottom-right resize:screenSizeX/2;screenSizeY/2
```

I bind the aliases to the number pad.

_bindings:_

```
# Use the keys below to put the selected window
bind pad1:ctrl;alt  ${bottomleft}
bind pad3:ctrl;alt  ${bottomright}
bind pad7:ctrl;alt  ${topleft}
bind pad9:ctrl;alt  ${topright}
```

more here:
https://gist.github.com/jgpawletko/9527674

I hope this helps...

**Comment by loshlee** [comment]
Ah, I see I ignored that the height needed to be half. Not the first time. Oh, well.

**Comment by abbood** [comment]
answered [here](http://superuser.com/questions/743214/how-to-make-four-windows-of-the-same-app-fill-four-quadrants-of-a-screen-using-s)
