### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by trevordmiller** [jigish/slate#419]
Not really an issue. I just wanted to say that Slate is absolutely amazing. Great work!

**Comment by sdegutis** [comment]
:+1:

**Comment by jonprasetyo** [comment]
Yes I totally agree. However, Yosemite is out now and I was wondering that it will work fine?

**Comment by jonprasetyo** [comment]
Oh Sorry, yes, it works! I just read the other issue.

**Comment by john-kurkowski** [comment]
+1. Never had an issue since 1.0. Not really hungering for updates either. It just works.

**Comment by osmancrush** [comment]
+100 awesome work - sorry been using it for years and never thanked you. Donation page?

**Comment by gabamnml** [comment]
+1

**Comment by dwtj** [comment]
:+1:
