### ISSUE TITLE
Consider adding UI options for basic snapshot management

### ISSUE THREAD

**Issue by philc** [jigish/slate#42]
The most common use of snapshots is probably to save and then later restore windows when unplugging a laptop from a monitor setup. For that use case, a menu option would be nice to have, because it requires no slate config setup, and it's not used often enough dedicate a whole hotkey to it (I sat down and tried, but couldn't pick something I would remember).

Adding a very basic UI for this (save/restore current state) will make it a drop-in replacement for Stay.

**Comment by jigish** [comment]
added in 0.4.17
