### ISSUE TITLE
Slate on Mavericks doesn't work

### ISSUE THREAD

**Issue by ShL519** [jigish/slate#424]
I had installed Slate,and created a ~/.slate.js file which is the same as Tristan Hume, and i had enable the accessibility... , however ,when i press the shortcut ,it seems that nothing happens even though i relaunch lots of times . Does anyone else get in the same situation? just want to know why :-)

**Comment by landau** [comment]
Slate worked fine for me on Mavericks. However, I just upgraded to Yosemite beta and it doesn't work!

Scratch that: https://github.com/jigish/slate/issues/405

**Comment by danieldisu** [comment]
I've get it working ( with problems on restart... ):
-   Remove it from accessibility
-   Add it to accessibility and enable it
-   change the name of the .slate.js to slate_something.js
-   run slate
-   change the name back to .slate.js
-   reload slate conf in slate context menu

**Comment by dasuchin** [comment]
I'm following this and using the config he shows, but it's not working: http://thume.ca/howto/2012/11/19/using-slate/

Do I have to do something different with hyper? I'm just leaving it as ctrl;shift;alt;cmd but none of the commands actually work.

**Comment by ghost** [comment]
Hi guys, at first Slate didn't work for me and every time I restarted my macbook, it told me that I should enable Accessibility. Later, I unchecked and re-checked the Accessibility for Slate, restarted it and it worked! I hope it helps you.

**Comment by ShL519** [comment]
thanks.I change the .slate.js file to .slate and relaunch and reload configuration file.Finally it works. : )
