### ISSUE TITLE
anyway to remove startup popup in OS X 10.10

### ISSUE THREAD

**Issue by zhuangya** [jigish/slate#434]
![2014-11-06 10 20 08](https://cloud.githubusercontent.com/assets/499038/4954708/01080b38-668f-11e4-9fd7-64b4fe4dc0a9.png)

after upgraded to OS X 10.10, everytime i turn on the computer, the popup above show up.

even if i check the "privacy checkbox" in the system preference as below:

![image](https://cloud.githubusercontent.com/assets/499038/4954737/3b1943aa-668f-11e4-8c39-e38965c839cb.png)

anyway to prevent it show up?

**Comment by dongyuwei** [comment]
see https://github.com/jigish/slate/issues/405

**Comment by zhuangya** [comment]
@dongyuwei thanks, closing this.
