### ISSUE TITLE
A command to tell Slate to quit

### ISSUE THREAD

**Issue by digitalronin** [jigish/slate#446]
I love slate, but there are some occasions when I need to free up the keyboard shortcuts I've got bound to it (e.g. Ctrl-Space is a shortcut key on duolingo.com, but it's also my slate hotkey).

Currently, I get around that by using the mouse to quit slate, then launching it again via spotlight, when I'm done. It would be great to have a key combo that I could bind to "quit", in the same way as I have one bound to "relaunch".

Thanks again for an awesome utility.

**Comment by chdiza** [comment]
(Untested, but should work): Bind the hotkey of your choice to: `shell '/usr/bin/osascript -e "tell app \"Slate\" to quit"'`

**Comment by digitalronin** [comment]
I couldn't get it to work inline, but wrapping the command up in a shell script and then invoking the script by binding it to a hotkey works fine;

```
bind q:${hotkey} shell /Users/david/bin/quit_slate.sh
```

Thanks for the tip.
