### ISSUE TITLE
.tar.gz and .dmg downloads bad

### ISSUE THREAD

**Issue by rbaindourov** [jigish/slate#451]
Hi,

Sorry. I Just tried to download the images linked in the readme, but I had a problem first with the dmg, unrecognized image, and a similar issue with the tar file.

Thanks.

**Comment by mattr-** [comment]
What release of OS X are you on?

On Tue, Sep 15, 2015 at 2:51 PM, Robert Baindourov <notifications@github.com

**Comment by rbaindourov** [comment]
Yosemite. 
10.10.4 (14E46)

**Comment by mattr-** [comment]
I just tried the .dmg on 10.10.5 and didn't have any problems. Could you try again? I'm thinking the downloads just didn't completed correctly and that's what's causing the issue.
