### ISSUE TITLE
Does Slate work with Adobe and JetBrains products?

### ISSUE THREAD

**Issue by davestewart** [jigish/slate#477]
Hello,

Looks like a great bit of software here!

Before I deep dive, can you tell me if Slate is able to manage windows from applications like Adobe Photoshop and JetBrains WebStorm / PHPStorm / IntelliJ ?

Cheers :)

**Comment by elwayman02** [comment]
Yes, I use it with WebStorm

**Comment by davestewart** [comment]
Oh, amazing. I gotta try this out!
