### ISSUE TITLE
slate not starting up on macos sierra?

### ISSUE THREAD

**Issue by sameerparekh** [jigish/slate#489]
After upgrading to sierra, when I launch slate it asks me the access question. I click enable, it doesn't prompt me for my admin password, and the slate icon disappears from my menubar.

**Comment by kevin-chau** [comment]
I was able to set up slate for macOS Sierra 10.12.

You may have to go to System Preferences>Security & Privacy>Accessibility

Then check the box next to Slate.app

After doing this slate should have access, and should run smoothly. Let me know if you're still having issues.

**Comment by sameerparekh** [comment]
That did it, thanks!
