### ISSUE TITLE
Consider making window hints less customizable 

### ISSUE THREAD

**Issue by philc** [jigish/slate#49]
The README lists these as customizable parameters:

```
windowHintsFontColor
windowHintsFontName
windowHintsFontSize
windowHintsRoundedCornerSize
windowHintsBackgroundColor

windowHintsTopLeftX
windowHintsTopLeftY
```

If you provide a nice UI out of the box, none of these will be needed.  Having customizable behavior is nice, but having customizable appearance limits what you can do in the future. If you wanted to add a nice visual effect upon selection (e.g. animating the text color from white->yellow), you can't, because you don't control the appearance.

In particular, letting users specify the hint positioning prevents you from doing smart hint placement in the future. A really nice feature would be to show a hint in the upper left corner _or_ the center of the app, depending on which is visible. This happens to me all the time now -- I'll have a terminal which obscures the left side of some window, and I can't select those underlying windows using window hints, because their upper left corner is hidden (but the rest of the window is visible).

It's up to you, but I'd rather you take control of the aesthetic instead of letting the user mess with it so that you can provide a nice one and keep your software and README simpler.

**Comment by jigish** [comment]
Thought about this a lot and I think I'm going to keep it complicated. I build slate thinking that I wanted to make it extremely customizable. While I understand the points, I think I should be able to still add cool features while still keeping it customizable (like the upper-left or center feature I've already added). If it starts becoming crazy I'll rethink.
