### ISSUE TITLE
Consider showing a window hint in the center of the window by default

### ISSUE THREAD

**Issue by philc** [jigish/slate#52]
This may require some research & asking around (Dmac may have an opinion about this) to validate whether centered is actually better than in the upper left.

Anecdotally, when I'm looking at windows and quickly switching between them, my eyes are focused in the center of the window, waiting for the hint character to show, not the upper left corner. For me it's a slight annoyance to have to look at the upper left corner of the window, wait for the character, type it, and then focus back again on the center of the window.

**Comment by dmac** [comment]
One way to do this might be to expose `windowSize{X,Y}` when setting `windowHintsTopLeft{X,Y}`, to make it configurable. Then to center it I could just say

```
windowHintsTopLeftX = windowSizeX/2
windowHintsTopLeftY = windowSizeY/2
```

**Comment by philc** [comment]
Although that configurability will complicate the implementation of https://github.com/jigish/slate/issues/50

**Comment by jigish** [comment]
Hmm, so theoretically you should be able to do that already. I'm pretty sure I tested that. In the "Expressions" section of the readme anything that is not explicitly stated to not be allowed in a certain location is allowed everywhere. The only problem is I currently test a point near the top left for visibility regardless of where the hint is configured to be placed. I would need to change the hint operation to test the center of the hint for visibility instead. In relation to issue #50, I could just have it default to the "smart" option and the configurations would override that to change it to be a fixed position.

**Comment by jigish** [comment]
And for the record to center it you need to do:

config windowHintsTopLeftX (windowSizeX/2)-(windowHintsWidth/2)
config windowHintsTopLeftY (windowSizeY/2)-(windowHintsHeight/2)

Just tried it with the latest build and it works.

**Comment by dmac** [comment]
Ah, works like a charm. Thanks!

**Comment by jigish** [comment]
Great! keeping this open until I fix the visibility thing. once I fix that I'll close this and try to make the default the "smart" location suggested in issue #50

**Comment by jigish** [comment]
Just made the visibility change. Closing this issue even though center is not default because issue #50 sort of negates it. I'm planning on implementing the default to be center + top-left fallback and will track that change in issue #50.

**Comment by jigish** [comment]
change will be available in the next build. likely 0.4.19
