### ISSUE TITLE
macOS Big Sur 11.1.0.1 (20B29) unresponsive window resizes

### ISSUE THREAD

**Issue by sunapi386** [jigish/slate#525]
Yes, I have enabled access in settings. Previously worked before upgrading to Big Sur. I was on Mojave. 

<img width="668" alt="Screen Shot 2020-11-15 at 14 22 18" src="https://user-images.githubusercontent.com/1029022/99198521-092fec00-274e-11eb-9b03-fd6bdc611177.png">

Using "relaunch and load config" gives this prompt
![image](https://user-images.githubusercontent.com/1029022/99198538-2b296e80-274e-11eb-9352-eda07f817a6e.png)

Even if selecting 'enable' there is no effect.

**Comment by ciprianimike** [comment]
This happened to me too.

Verify Slate is checked in the Accessibility permissions screen.

Quit and restart slate, It works on Big Sur

<img width="669" alt="Screenshot 2020-11-16 at 03 33 38" src="https://user-images.githubusercontent.com/5706607/99206806-9742bb80-27bc-11eb-880d-1a2cb2ec5508.png">

**Comment by jamesblanksby** [comment]
@ciprianimike I had to toggle the checkbox off and on in Accessibility permissions and then restart. Thanks!

**Comment by deusofka** [comment]
@jamesblanksby In my case, the checkbox failed to uncheck. So, I had to press the minus sign to remove Slate and add it back again!

**Comment by sunapi386** [comment]
@anthropX this worked for me. Could not uncheck it. Select it, minus sign, then plus sign, find and add the Slate.app. Relaunch Slate and it works again. Closing.

**Comment by ciprianimike** [comment]
> @ciprianimike I had to toggle the checkbox off and on in Accessibility permissions and then restart. Thanks!

I'm glad it was useful, I am addicted to Slate on Mac OS
