### ISSUE TITLE
Slate not working on Big Sur

### ISSUE THREAD

**Issue by rahulgi** [jigish/slate#526]
After upgrading to Big Sur, Slate doesn't seem to be able to manage any of my windows anymore.

I think it might be a permissions issue - if I relaunch Slate it complains that "Slate cannot run without "Access for assistive devices" ". However, if I got to the Security and Privacy menu, Slate is checked under the "Accessibility" and "Automation" sections, and I'm not able to find anything else with the title "Access for assistive devices" that the Slate message mentioned.

Anybody have any luck getting Slate to work on Big Sur?

**Comment by manijshrestha** [comment]
This project has not been maintained for years, you might want to checkout out hammerspoon. https://github.com/Hammerspoon/hammerspoon

**Comment by frifox** [comment]
I had to enable Slate in Accessibility section as well as manually add it to the Input Monitoring. After that it worked as before

**Comment by uyendee** [comment]
This worked after playing with various different privacy and access options for me. 
I was trying to get used to https://rectangleapp.com/ but still struggling when I sorted Slate out.

**Comment by rahulgi** [comment]
Hmm, unfortunately I wasn't able to figure it out even after trying to play around with the various settings. Switched to [Yabai](https://github.com/koekeishiya/yabai) and it seems to be working out :)

**Comment by harciga** [comment]
It's working fine under 11.0.1.

**Comment by emathias** [comment]
In my case in Settings > Privacy > Accessibility, Slate was activated. I had to deactivate and reactivate and now it's working again

**Comment by xuzhao9** [comment]
> In my case in Settings > Privacy > Accessibility, Slate was activated. I had to deactivate and reactivate and now it's working again

Confirmed it works on my laptop. Thank you very much!

**Comment by hackergil** [comment]
> In my case in Settings > Privacy > Accessibility, Slate was activated. I had to deactivate and reactivate and now it's working again

This worked for me too. Thank you!

**Comment by rahulgi** [comment]
Oof, can't believe I never tried the "turn it off and turn it on again" method haha.

**Comment by tapsboy** [comment]
Settings > Privacy > Accessibility

I had to remove slate (not unselect checkbox, but press minus to remove) , quit the app, launch it again, press enable on dialog box and then it showed up again and then select checkbox

**Comment by sgmcb** [comment]
Echoing tapsboy: I had to remove Slate entirely (minus button, not the checkbox) and re-add ("+") for the Slate app to stop giving me this error:

> Slate cannot run without "Access for assistive devices". Would you like to enable it?
> You may be prompted for your administrator password.

 
(The OS never actually prompted me for my admin password, though.)

**Comment by ciprianimike** [comment]
> I had to enable Slate in Accessibility section as well as manually add it to the Input Monitoring. After that it worked as before

this solves the issue, Slate was not even added in the Input Monitor section, as unselected checkbox.

This issue should be opened as a new one unrelated to Big Sur

**Comment by fmquaglia** [comment]
If it's helpful to anyone out there... I just updated to OSX v12.5 (Monterey), and Slate stopped working.

To fix it, I had to :
* Quit Slate
* Delete Slate entries from `Settings > Privacy > Accessibility` and `Settings > Privacy > Input monitoring`
* Add Slate again, manually to `Settings > Privacy > Accessibility` and `Settings > Privacy > Input monitoring`

... profit.
