### ISSUE TITLE
starter/example .slate file

### ISSUE THREAD

**Issue by gregwebs** [jigish/slate#53]
Are there some example .slate files? Perhaps you can enable the wiki and ask for some examples from current users.

**Comment by jigish** [comment]
I have mine up here: https://github.com/jigish/dotfiles/blob/master/slate

But you make a good point. I'll activate the wiki and try to get some examples up there. Will keep this issue open to track the wiki progress.

**Comment by jigish** [comment]
Some of the users have added their example slate files. more to come. I'll add examples to the wiki when I get time. Closing this issue.

**Comment by gregwebs** [comment]
thanks, I am actually going to give slate a go now :)

**Comment by jigish** [comment]
Awesome! Please let me know if you have any issues or questions: slate.issues@gmail.com. I can definitely help you through configuring it if need be. I completely understand that it can be a daunting task at first :)
