### ISSUE TITLE
Window hints are not shown for many windows

### ISSUE THREAD

**Issue by philc** [jigish/slate#58]
As of 2001a33 (I had to build from source; the binary that's checked in is broken).

See screenshot here -- only one window is hinted.

http://i.imgur.com/TULA5.jpg

I've also seen the hint characters glitch from the center to the upper left, and chrome windows not be focusable if the dev console is showing (almost like it gets treated as its own window with a centered hint).

**Comment by jigish** [comment]
ok that is really weird. what OS version are you running? I just tried three windows and it works just fine. then tried chrome+console and it worked. Hints are now center first with top-left backup if the center point is not visible.

Also, how was the binary broken?

**Comment by philc** [comment]
The state shown in the screenshot happens over time, although while trying to reproduce some other bugs I was able to get it pretty quickly: http://i.imgur.com/9dsQc.png

I can show you when you're next in the office.

I'll file a separate bug for the center -> upper left flicker when I have a more detailed repro case.

**Comment by philc** [comment]
I've found a reproducible case which may be the root cause of this bug, or a separate bug.

Steps to reproduce:
1. Hide or minimize all windows
2. Focus an application (like textmate), create a new window, and activate link hints, and close that new window.
3. Repeat #2 over and over, cycling through hint characters

You'll notice that some of these new windows do not get hint characters.

**Comment by jigish** [comment]
I _think_ I've fixed the problem. It seems like it was in the code where I detect new windows forming. Some applications spawn new windows with empty titles (which I was ignoring) then change the titles later. I've now fixed it such that when the title changes it adds the window properly. Hopefully this fixes the problem. If not, I've fixed part of the problem. The fix will be available in the next release. Please re-open this issue if you still see the problem.
