### ISSUE TITLE
Window hints cannot focus the iterms preferences window

### ISSUE THREAD

**Issue by philc** [jigish/slate#63]
Steps to reproduce:
1. Open item's preferences window
2. Try to focus it using window hints. It doesn't get focused.

Not very important, but I thought it was a little strange.

**Comment by jigish** [comment]
Seems like the accessibility wrapper can't focus the preference window for some reason. Maybe the type of window it is. I've changed focus to still bring the main window of the app to the front if it can't focus the window which should be a _bit_ better. Closing this issue, but I'll keep looking for solutions to this.
