### ISSUE TITLE
After opening up two fresh terminal windows, their hints collide

### ISSUE THREAD

**Issue by philc** [jigish/slate#64]
The windows are the same size and have the same title.

**Comment by jigish** [comment]
This is because their titles are the same. I need to find a way to get around this. I'm thinking I should use title and top-left to differentiate between windows, but tracking windows as they move may not be possible.

**Comment by jigish** [comment]
for now, this and issue #65 should be "fixed" by setting the config:

`config windowHintsOrder leftToRight`

**Comment by jigish** [comment]
this should be fixed by 16b7df309ab413361eb16ad05b8d9f70ca47a316

If not please reopen.

Either way setting the config should get rid of the problem for sure.

**Comment by philc** [comment]
lgtm
