### ISSUE TITLE
Periodically, a new window cannot be hinted

### ISSUE THREAD

**Issue by philc** [jigish/slate#65]
In my experience, this happens for about 1 in 15 windows. I've definitely seen it happen for iTerm2 windows, and I believe I recall it happening for textmate and chrome.

**Comment by philc** [comment]
Actually, this also affects existing windows, which is really annoying. I just saw a case where I had a terminal window with history etc. which I'd been using for a few hours, and it suddenly stopped being hintable.

The workaround is to restart Slate, which I do a few times per hour to work around this and the desktops bug.

**Comment by jigish** [comment]
Wow thats frustrating. I totally thought I fixed this. Will check it out again. It may be related to the title thing (Issue #64).

**Comment by jigish** [comment]
for now, this and issue #64 should be "fixed" by setting the config:

`config windowHintsOrder leftToRight`

**Comment by jigish** [comment]
this should be fixed by 16b7df309ab413361eb16ad05b8d9f70ca47a316

If not please reopen.

Either way setting the config should get rid of the problem for sure.
