### ISSUE TITLE
0.5.6 release build dies with nib error

### ISSUE THREAD

**Issue by philc** [jigish/slate#68]
4/26/12 1:55:23.638 PM Slate: Unable to load nib file: MainMenu, exiting
4/26/12 1:55:23.639 PM com.apple.launchd.peruser.561: ([0x0-0x611611].com.slate.Slate[26081]) Exited with code: 1

This only happens when the application is moved into /Applications. If run directly from the git repo file system, it works.

Also, this release build does not appear to have an icon.

**Comment by jigish** [comment]
ok this is interesting. I'm not having this problem at all. I'm going to be generating a new release soon. I'll keep this issue open and check with you when I release it.

**Comment by jigish** [comment]
0.5.7 has been released. This should be fixed. I think it was due to me code-signing the last release.

**Comment by philc** [comment]
lgtm, and this release build has an icon. Closing.
