### ISSUE TITLE
Disconnecting/Reconnecting Monitor switches screen ID

### ISSUE THREAD

**Issue by jigish** [jigish/slate#7]
The screen IDs defined in the .slate file change when Disconnecting/Reconnecting Monitors in the wrong order.

**Comment by jigish** [comment]
maybe define screen alias based on resolution?

**Comment by jigish** [comment]
fixed by allowing screen resolution and/or orientation

**Comment by JerryWho** [comment]
Can you give an example how I define screen aliases based on resolution?
