### ISSUE TITLE
Slate ignores Dvorak keyboard layout

### ISSUE THREAD

**Issue by harob** [jigish/slate#70]
It just acts as if I'm in Qwerty mode. I can work around this in the config file (by putting what the key would be qwerty), but it makes keyboard window hints unusable.

**Comment by jigish** [comment]
Fixed in 0.5.9.

**Comment by drgrib** [comment]
This is happening again in 1.0.25. Slate only uses the hardcoded QWERTY key for window hints and ignores that I am in Dvorak.

**Comment by wkf** [comment]
@drgrib have you tried adding `config keyboardLayout dvorak` to your slate config?

**Comment by drgrib** [comment]
@wkf Yes, I discovered that setting in another thread and it worked. Thanks for putting it in this one for posterity.
