### ISSUE TITLE
Some directives in the sample config do not work

### ISSUE THREAD

**Issue by lopopolo** [jigish/slate#71]
```
bind right:ctrl resize +10% +0
bind left:ctrl  resize -10% +0
```

These key combinations don't get fired because ctrl+<left> and ctrl+<right> are used for switching spaces.

Ctrl+up and Ctrl+down activate/deactivate Mission Control on Lion.

Ctrl+Shift+down is app expose, ctrl+shift+up is regular expose

**Comment by jigish** [comment]
Yah I'm aware of this. I'm not going to change them but I'll add a note saying that you have to get rid of expose/spaces/mission control bindings.

**Comment by jigish** [comment]
added comments to my config.

**Comment by jigish** [comment]
and updated read me to reflect this
