### ISSUE TITLE
Odd 'Unable to parse binding' Error

### ISSUE THREAD

**Issue by eipark** [jigish/slate#73]
This line:

```
layout air-tb 'iTerm' throw 0 resize | corner top-right resize:${full}
```

works fine, but this:

```
layout air-tb 'iTerm' throw 0 resize | corner top-right resize:${half-width}
```

throws the unable to parse binding error, where the aliases are:

```
alias full screenSizeX;screenSizeY
alias half-width screenSizeX/2;screenSizeY
```

Any ideas? I'm stumped. I have similar layout directives using the same aliases I've had in my config for a long time, but certain ones don't seem to work.

**Comment by jigish** [comment]
hmm. I just tried adding this on my config and it works. just running through the common errors:
1. aliases must be defined before they are used
2. make sure you don't have two aliases with the same name
3. try renaming the alias maybe?

Other than that you can send me your entire .slate and I'll try it out.

Also, what version are you running?

**Comment by jigish** [comment]
Hey man, is this still an issue or can I close it?

**Comment by eipark** [comment]
Closr

---

Ernie Park
Massachusetts Institute of Technology 2012
Electrical Engineering & Computer Science
362 Memorial Drive | Cambridge, MA 02139
618.744.9624 | www.erniepark.com

On Sep 7, 2012, at 10:55 AM, Jigish Patel notifications@github.com wrote:

Hey man, is this still an issue or can I close it?

—
Reply to this email directly or view it on
GitHubhttps://github.com/jigish/slate/issues/73#issuecomment-8373252.
