### ISSUE TITLE
Bind numbers does not work for numeric keypad

### ISSUE THREAD

**Issue by timmow** [jigish/slate#81]
I am using the following config setting

bind 1:cmd;alt corner bottom-left resize:screenSizeX/2;screenSizeY/2

And this works fine using the 1 key along the top row of they keyboard - however, it does nothing when using the 1 key on the numeric keypad.

I'm using slate 1.0.2 and the keyboard layout is British if that helps at all.

**Comment by jigish** [comment]
not sure if you noticed this already but the num pad uses the prefix "pad" so it should be:

```
bind pad1:cmd;alt corner bottom-left resize:screenSizeX/2;screenSizeY/2
```
