### ISSUE TITLE
Command Line Support

### ISSUE THREAD

**Issue by jigish** [jigish/slate#85]
Allow users to call bindings from the command line. For example:

`$ slate activate ctrl:1` should activate the binding for the keypress `ctrl+1`

**Comment by jigish** [comment]
As mentioned in Issue #78, add a bind operation for shell scripts as well.

**Comment by jigish** [comment]
And as mentioned in Issue #112, add before/after hooks for shell scripts

**Comment by jigish** [comment]
I've added the `shell` operation. Will be available in 1.0.12. I'm keeping this open until I implement a command line version of slate.

**Comment by philc** [comment]
hawt. Scriptable ftw!

**Comment by philc** [comment]
I don't have a use case for the command line integration, but it seems to me this would have more power if scripts could just invoke slate commands directly, rather than dealing with the bindings abstraction. e.g. `slate run throw 0`

**Comment by clarkewd** [comment]
I would also really like to see the option to activate bindings from the command line. SublimeText adds a little utility:

```
/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl
```

I guess when the CLI integration is added to slate then it will be added to the documentation? I don't want to miss it when it comes out.

**Comment by clarkewd** [comment]
fyi - i would be willing to make a donation for shell support

**Comment by digitaldesigndj** [comment]
:+1: This would be really awesome, I think it would be cool to use something like [Alfred](http://www.alfredapp.com/) to show and hide less frequently used program windows.

**Comment by zhaocai** [comment]
:+1: Integrate with Alfred would be nice.

**Comment by fredcallaway** [comment]
Safe to say this won't happen at this point. For mac, a workaround is to simulate a keypress with applescript:

```
bind pad7 layout coding # in ~/.slate
osascript -e 'tell application "System Events" to keystroke "7"'  # bash
```
