### ISSUE TITLE
Building for 32 bit processors?

### ISSUE THREAD

**Issue by pygy** [jigish/slate#88]
I still have a 32 bit machine, and, since the pre-compiled binary is 64 bit-only, I've tried to compile Slate by myself.

I'm running Snow Leopard and Xcode 3.2.6 (I didn't get 4.0 while it was out). I assume that it is the problem, but I'm not sure.

Building fails, both in 32 and 64 bit modes.

The relevant parts of the build log can be found here: https://gist.github.com/3804989

**Comment by jigish** [comment]
Hmm by looking at the log I'm pretty sure the issue is that your version of Xcode doesn't support ARC. If you can update your Xcode to a version that does and try it out you may have better luck. I'll see if there are any options to build in a 32 bit binary as part of my build process but I can't say for sure yet.

**Comment by pygy** [comment]
Thanks for checking this out.

I'll soon have access to a machine with OS X 10.8, I'll give a try at a
universal build and report back.

**Comment by jigish** [comment]
Just looked in to this. Unfortunately I am using ARC in my project and I didn't realize this earlier but 32-bit is explicitly not supported by Apple's LLVM compiler when using ARC. Leave it to Apple to ninja-kill configurations randomly. Converting my project to non-ARC is not really in the cards as it would take a long time and I just recently flipped from non-ARC to ARC. Sorry the answer isn't good news =/.

**Comment by pygy** [comment]
No problem. That machine is 6 years old, and won't last much longer (it
only works on AC and without a battery, the left I/O board overheats badly
otherwise up to 110ºC)).

I'll use Slate on the new one. :-)
