### ISSUE TITLE
Key bindings not respecting keyboard layout

### ISSUE THREAD

**Issue by santip** [jigish/slate#99]
I use a dvorak keyboard layout yet slate bindings are recognizing keys by the hardware location in a qwerty layout. This is happening both in direct bindings in the config and with the hinted characters in the window hints functionality.

**Comment by jigish** [comment]
check out Issue #70

Basically if you add following config it should work:

`config keyboardLayout dvorak`

**Comment by santip** [comment]
apologies for the duplication, when I first searched for preexisting issues I had assumed that this only happened in the hints functionality so that narrowed my search :)

**Comment by stouset** [comment]
Out of curiosity, why should there be a configuration option for this? Why shouldn't it "just work"? It seems like requiring a configuration file for every keyboard layout under the sun will be an annoying duplication of effort that just isn't necessary.

**Comment by jigish** [comment]
not really sure how it can "just work"? Each keyboard layout maps different physical keys to different key codes. I couldn't really find a reliable way to determine which layout is currently selected for the user and even if I did I'd still need to create a mapping file for it as I doubt OS X exposes the mapping. So this seemed like the next best option to me. If you know of a better way to do this please let me know. I don't really like having to create (or ask for someone to create) a new mapping file each time someone wants a new keyboard layout added to slate.

**Comment by stouset** [comment]
A little Googling turned up [some code](http://inquisitivecocoa.com/2009/04/key-code-translator/) to translate keycodes into keys (and key names) through the keyboard layout using Cocoa.

No idea if it still works, or if it actually helps to solve the problem for your use-case. Thoughts?
